<?php 
 include('header.php');
include('database/conn.php'); 
$query_parent = mysqli_query($conn,"SELECT * FROM `regtype`") or die("Query failed: ".mysql_error());

?>
<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    
	$("#parent_cat").change(function() {
		$(this).after('<div id="loader"><img src="img/loading.gif" alt="loading subcategory" /></div>');
		$.get('loadsubcat.php?parent_cat=' + $(this).val(), function(data) {
			$("#asdf_cat").html(data);
			$('#loader').slideUp(200, function() {
				$(this).remove();
			});
		});	
    });

});

$(document).ready(function() {
    
	$("#asdf_cat").change(function() {
		$(this).after('<div id="loader"><img src="img/loading.gif" alt="loading subcategory" /></div>');
		$.get('loadsubcat.php?asdf_cat=' + $(this).val(), function(data) {
			$("#sub_cat").html(data);
			$('#loader').slideUp(200, function() {
				$(this).remove();
			});
		});	
    });

});
</script>
  
  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Zamfara State Internally Generated Revenue System</p>

      <form action="createaccount.php" method="post">
		  <div class="row">
	    <div class="col-md-6">
		        <div class="input-group mb-3">
				  <select class="form-control select2" required name="vehiclemake" style="width: 100%;">
<option selected="selected" disabled="disabled" value="">Select Vehicle Make</option>
				<option value="">-Select Vehicle-Make-</option>
				<option value="Others">Others</option>
				<option value="ACURA">ACURA</option>
				<option value="ASTON MARTIN">ASTON MARTIN</option>
				<option value="AUDI">AUDI</option>
				<option value="BMW">BMW</option>
				<option value="BUICK">BUICK</option>
				<option value="CADILLAC">CADILLAC</option>
				<option value="CHEVROLET">CHEVROLET</option>
				<option value="BENTLEY">BENTLEY</option>
				<option value="ALFA ROMEO">ALFA ROMEO</option>
				<option value="AM GENERAL">AM GENERAL</option>
				<option value="CHEVROLET TRUCK">CHEVROLET TRUCK</option>
				<option value="CHRYSLER">CHRYSLER</option>
				<option value="DAEWOO">DAEWOO</option>
				<option value="DATSUN">DATSUN</option>
				<option value="FERRARI">FERRARI</option>
				<option value="FORD">FORD</option>
				<option value="VOLVO">VOLVO</option>
				<option value="VOLKSWAGEN">VOLKSWAGEN</option>
				<option value="OPEL">OPEL</option>
				<option value="SATURN">SATURN</option>
				<option value="TOYOTA">TOYOTA</option>
				<option value="PEUGEOT">PEUGEOT</option>
				<option value="LINCOLN">LINCOLN</option>
				<option value="SAAB">SAAB</option>
				<option value="MITSUBISHI">MITSUBISHI</option>
				<option value="NISSAN">NISSAN</option>
				<option value="MERCEDES-BENZ">MERCEDES-BENZ</option>
				<option value="MAZDA">MAZDA</option>
				<option value="MERCURY">MERCURY</option>
				<option value="NFINITI">NFINITI</option>
				<option value="HONDA">HONDA</option>
				<option value="HUMMER">HUMMER</option>
				<option value="YUGO">YUGO</option>
				<option value="TRIUMPH">TRIUMPH</option>
				<option value="TVR">TVR</option>
				<option value="SUZUKI">SUZUKI</option>
				<option value="AUSTIN HEALEY">AUSTIN HEALEY</option>
				<option value="DAIHATSU">DAIHATSU</option>
				<option value="BRICKLIN">BRICKLIN</option>
				<option value="BUGATTI">BUGATTI</option>
				<option value="CITROEN">CITROEN</option>
				<option value="FIAT">FIAT</option>
				<option value="FORD TRUCK">FORD TRUCK</option>
				<option value="GMC TRUCK">GMC TRUCK</option>
				<option value="ISUZU">ISUZU</option>
				<option value="GMC">GMC</option>
				<option value="DODGE">DODGE</option>
				<option value="HYUNDAI">HYUNDAI</option>
				<option value="JEEP">JEEP</option>
				<option value="SALEEN">SALEEN</option>
				<option value="LAMBORGHINI">LAMBORGHINI</option>
				<option value="JAGUAR">JAGUAR</option>
				<option value="LANCIA">LANCIA</option>
				<option value="PONTIAC">PONTIAC</option>
				<option value="KIA KIA">KIA KIA</option>
				<option value="LEXUS">LEXUS</option>
				<option value="LAND ROVER">LAND ROVER</option>
				<option value="KIA">KIA</option>
				<option value="LOTUS">LOTUS</option>
				<option value="PACKARD">PACKARD</option>
				<option value="OLDSMOBILE">OLDSMOBILE</option>
				<option value="PLYMOUTH">PLYMOUTH</option>
				<option value="SUBARU">SUBARU</option>
				<option value="MAYBACH">MAYBACH</option>
				<option value="RENAULT">RENAULT</option>
				<option value="ROLLS-ROYCE">ROLLS-ROYCE</option>
				<option value="STUDEBAKER">STUDEBAKER</option>
				<option value="SCION">SCION</option>
				<option value="MASERATI">MASERATI</option>
				<option value="MAN">MAN</option>
				<option value="TOYOTA CARINA">TOYOTA CARINA</option>
				<option value="PASSAT">PASSAT</option>
				<option value="LIFAN">LIFAN</option>
				<option value="ROVER">ROVER</option>
				<option value="JINCHENG">JINCHENG</option>
				<option value="HONDA CIVIC">HONDA CIVIC</option>
				<option value="HONDA CIVIC SHUTTLE">HONDA CIVIC SHUTTLE</option>
				<option value="TOYOTA CAMRY">TOYOTA CAMRY</option>
				<option value="LORRY">LORRY</option>
				<option value="LEYLAND">LEYLAND</option>
				<option value="BAJAJ">BAJAJ</option>
				<option value="CARINA E">CARINA E</option>
				<option value="HONDA ACCORD">HONDA ACCORD</option>
				<option value="MOTOR-CYCLE">MOTOR-CYCLE</option>
				<option value="QLINK">QLINK</option>
				<option value="MOTOR CYCLE">MOTOR CYCLE</option>
				<option value="BOXERS">BOXERS</option>
				<option value="DAF">DAF</option>
				<option value="VILLAGER">VILLAGER</option>
				<option value="BEDFORD">BEDFORD</option>
				<option value="AUSTIN">AUSTIN</option>
				<option value="CABSTER ">CABSTER </option>
				<option value="SKYGO">SKYGO</option>
				<option value="MACK">MACK</option>
				<option value="TOYOTA COROLLA">TOYOTA COROLLA</option>
				<option value="TOYOTA STARLET">TOYOTA STARLET</option>
				<option value="VOLKSWAGEN JETTA">VOLKSWAGEN JETTA</option>
				<option value="CHEROKEE JEEP">CHEROKEE JEEP</option>
				<option value="JETTA">JETTA</option>
				<option value="VENTRO">VENTRO</option>
				<option value="VOLKSWAGEN GOLF">VOLKSWAGEN GOLF</option>
				<option value="IVECO">IVECO</option>
				<option value="SINOKI">SINOKI</option>
				<option value="ZONGMACE">ZONGMACE</option>
				<option value="MONTERO JEEP">MONTERO JEEP</option>
				<option value="MAN DIESEL">MAN DIESEL</option>
				<option value="MAXIMA">MAXIMA</option>
				<option value="420">420</option>
				<option value="YAMAHA">YAMAHA</option>
				<option value="NISSAN QUEST">NISSAN QUEST</option>
				<option value="NISSAN PATHFINDER">NISSAN PATHFINDER</option>
				<option value="PREMIER">PREMIER</option>
				<option value="NISSAN PREMERA">NISSAN PREMERA</option>
				<option value="NISSAN PRIMERA">NISSAN PRIMERA</option>
				<option value="5 SERIES">5 SERIES</option>
				<option value="NISSAN PRAIRE">NISSAN PRAIRE</option>
				<option value="KASEA">KASEA</option>
				<option value="GEWLY MK">GEWLY MK</option>
				<option value="GEELY MK ">GEELY MK </option>
				<option value="NANFANG">NANFANG</option>
				<option value="HONDA BULLET">HONDA BULLET</option>
				<option value="PEUGEOT 505">PEUGEOT 505</option>
				<option value="BORD SEIRA">BORD SEIRA</option>
				<option value="SUPRA">SUPRA</option>
				<option value="SUZIKI SUPRA">SUZIKI SUPRA</option>
				<option value="NISSAN ALTIMA">NISSAN ALTIMA</option>
				<option value="NISSAN CABSTAR">NISSAN CABSTAR</option>
				<option value="SORENTO ">SORENTO </option>
				<option value="NISSAN SUNNY">NISSAN SUNNY</option>
				<option value="T.V.S.">T.V.S.</option>
				<option value="SEAT -TOLEDO">SEAT -TOLEDO</option>
				<option value="BLUE/BIRD">BLUE/BIRD</option>
				<option value="RAV 4">RAV 4</option>
				<option value="TOYOTA RAV 4">TOYOTA RAV 4</option>
				<option value="NISSAN PATROL">NISSAN PATROL</option>
				<option value="MIT LANCER">MIT LANCER</option>
				<option value="NISSAN BUS">NISSAN BUS</option>
				<option value="SNOKY  SIGMA">SNOKY  SIGMA</option>
				<option value="DEER">DEER</option>
				<option value="HIAB PICK-UP">HIAB PICK-UP</option>
				<option value="TATA BUS">TATA BUS</option>
				<option value="MAN TIPPER">MAN TIPPER</option>
				<option value="NISSAN STANZA">NISSAN STANZA</option>
				<option value="MITSUBISHI CANTER P/UP">MITSUBISHI CANTER P/UP</option>
				<option value="FOED SIERRA">FOED SIERRA</option>
				<option value="FORD SIERRA">FORD SIERRA</option>
				<option value="INFINITY">INFINITY</option>
				<option value="SIMBA">SIMBA</option>
				<option value="QINGQI">QINGQI</option>
				<option value="NISSAN B/BIRD">NISSAN B/BIRD</option>
				<option value="AUDI 80">AUDI 80</option>
				<option value="KANCHEN">KANCHEN</option>
				<option value="MAZDA 323">MAZDA 323</option>
				<option value="ZONGZHEN">ZONGZHEN</option>
				<option value="NISSAN VANETTE">NISSAN VANETTE</option>
				<option value="PIAGIO APE 3 WHEELER">PIAGIO APE 3 WHEELER</option>
				<option value="SKODA">SKODA</option>
				<option value="GOLF ">GOLF </option>
				<option value="GOLF P/UP">GOLF P/UP</option>
				<option value="GOLF PICK-UP">GOLF PICK-UP</option>
				<option value="ORRON FORD">ORRON FORD</option>
				<option value="NISSAN MAXIMA">NISSAN MAXIMA</option>
				<option value="OPEL OMEGA">OPEL OMEGA</option>
				<option value="TOYOTA CORROLA">TOYOTA CORROLA</option>
				<option value="NISSAN ATLAS">NISSAN ATLAS</option>
				<option value="FIAT TRUCK">FIAT TRUCK</option>
				<option value="GO WELL">GO WELL</option>
				<option value="MAZDA 626">MAZDA 626</option>
				<option value="UNDER ACCORD">UNDER ACCORD</option>
				<option value="NISSAN CHERRY">NISSAN CHERRY</option>
				<option value="100">100</option>
				<option value="MAGIRUS">MAGIRUS</option>
				<option value="PEUGEOT EXPERT">PEUGEOT EXPERT</option>
				<option value="HONDA ODDYSSEY">HONDA ODDYSSEY</option>
				<option value="WALL DEER">WALL DEER</option>
				<option value="PEUGEOT 504">PEUGEOT 504</option>
				<option value="TOYOTA SIENNA">TOYOTA SIENNA</option>
				<option value="NISSAN LAUREL">NISSAN LAUREL</option>
				<option value="OPEL ASTRA">OPEL ASTRA</option>
				<option value="TOYOTA 4 RUNNER">TOYOTA 4 RUNNER</option>
				<option value="OPEL KADET">OPEL KADET</option>
				<option value="DATSUN SUNNY">DATSUN SUNNY</option>
				<option value="DANCIA LOGAN">DANCIA LOGAN</option>
				<option value="TOYOTA LAND CRUISER">TOYOTA LAND CRUISER</option>
				<option value="FENCO">FENCO</option>
				<option value="MIT BUS">MIT BUS</option>
				<option value="OPEL VECTRA">OPEL VECTRA</option>
				<option value="200">200</option>
				<option value="V/WAGEN PASSAT">V/WAGEN PASSAT</option>
				<option value="DAEWOO LEGANZA">DAEWOO LEGANZA</option>
				<option value="DAEWO LEGANZA">DAEWO LEGANZA</option>
				<option value="DAEWOO  ESPERO">DAEWOO  ESPERO</option>
				<option value="PEUGEOT 306">PEUGEOT 306</option>
				<option value="TOYOTA TERCEL">TOYOTA TERCEL</option>
				<option value="CARGO SUPER">CARGO SUPER</option>
				<option value="TOYOTA LEXUS">TOYOTA LEXUS</option>
				<option value="BEDFORD MIDI">BEDFORD MIDI</option>
				<option value="TOYOTA PICKUP">TOYOTA PICKUP</option>
				<option value="MORRIS">MORRIS</option>
				<option value="TOYOTA PREVIA">TOYOTA PREVIA</option>
				<option value="FRAJEND">FRAJEND</option>
				<option value="MITSUBISHI GALLANT">MITSUBISHI GALLANT</option>
				<option value="BENZ200">BENZ200</option>
				<option value="TOYOTA HIACE">TOYOTA HIACE</option>
				<option value="190">190</option>
				<option value="FREDERICH">FREDERICH</option>
				<option value="VOLKSWAGOON">VOLKSWAGOON</option>
				<option value="DATSUN NISSAN">DATSUN NISSAN</option>
				<option value="AULTIMA">AULTIMA</option>
				<option value="TOYOTA HILUS">TOYOTA HILUS</option>
				<option value="OSAKI">OSAKI</option>
				<option value="FORD JEEP">FORD JEEP</option>
				<option value="NISSAN URVAN">NISSAN URVAN</option>
				<option value="BUSTER BUS">BUSTER BUS</option>
				<option value="FORD TIPPER">FORD TIPPER</option>
				<option value="NISSAN ALMERA">NISSAN ALMERA</option>
				<option value="PAJERO MITS">PAJERO MITS</option>
				<option value="OJAKI">OJAKI</option>
				<option value="SUZUKI RODEO">SUZUKI RODEO</option>
				<option value="NISSAN SECTRA">NISSAN SECTRA</option>
				<option value="NISSAN SENTRA">NISSAN SENTRA</option>
				<option value="MASOBI">MASOBI</option>
				<option value="MITSUBISHI COLT">MITSUBISHI COLT</option>
				<option value="TOYOTA AVALON">TOYOTA AVALON</option>
				<option value="MITSUBISHI SPACEWAGON">MITSUBISHI SPACEWAGON</option>
				<option value="DATSUN LAUREL">DATSUN LAUREL</option>
				<option value="TOYOTA CARINA 11">TOYOTA CARINA 11</option>
				<option value="CHRYSLER VOYAGER">CHRYSLER VOYAGER</option>
				<option value="KIA RIO">KIA RIO</option>
				<option value="FORLAND">FORLAND</option>
				<option value="ISUZU BUS">ISUZU BUS</option>
				<option value="MITSUBISHI MINI BUS">MITSUBISHI MINI BUS</option>
				<option value="M/BENZ V/BOOT">M/BENZ V/BOOT</option>
				<option value="NISSAN PICK UP">NISSAN PICK UP</option>
				<option value="PASSAT VENTO">PASSAT VENTO</option>
				<option value="TOYOTA DYNA">TOYOTA DYNA</option>
				<option value="KIA PREGIO">KIA PREGIO</option>
				<option value="NISSAN MURANO">NISSAN MURANO</option>
				<option value="M/BENZ 422">M/BENZ 422</option>
				<option value="MITSUBISHI L300">MITSUBISHI L300</option>
				<option value="MERCEDES-BENZ 230">MERCEDES-BENZ 230</option>
				<option value="NISSAN MICRA">NISSAN MICRA</option>
				<option value="MERCEDES-BENZ 190">MERCEDES-BENZ 190</option>
				<option value="EXPERT VAN ORDINA">EXPERT VAN ORDINA</option>
				<option value="LAND MASTER">LAND MASTER</option>
				<option value="RENAULT LAGUNA">RENAULT LAGUNA</option>
				<option value="VOLVO 740">VOLVO 740</option>
				<option value="HONDA PRELUDE">HONDA PRELUDE</option>
				<option value="DATSUN B/BIRD">DATSUN B/BIRD</option>
				<option value="VOLVO 240">VOLVO 240</option>
				<option value="STERY">STERY</option>
				<option value="KIA OPTIMC">KIA OPTIMC</option>
				<option value="TOYOTA PRADO">TOYOTA PRADO</option>
				<option value="HONDA CONCERTO">HONDA CONCERTO</option>
				<option value="FORD SCORPIO">FORD SCORPIO</option>
				<option value="HONDA CITY">HONDA CITY</option>
				<option value="BMW 5 SERIES">BMW 5 SERIES</option>
				<option value="VOLVO 245">VOLVO 245</option>
				<option value="FOTOU">FOTOU</option>
				<option value="AUDI 100">AUDI 100</option>
				<option value="NISSAN CABSTAR PLUP">NISSAN CABSTAR PLUP</option>
				<option value="TOYOTA CARINA E">TOYOTA CARINA E</option>
				<option value="HYUNDAI LANTRA">HYUNDAI LANTRA</option>
				<option value="MERCEDES-BENZ 200">MERCEDES-BENZ 200</option>
				<option value="PASSAT V/WAGEN">PASSAT V/WAGEN</option>
				<option value="PEUGEOT 406">PEUGEOT 406</option>
				<option value="NISSAN TERANO">NISSAN TERANO</option>
				<option value="HONDA CONSERTO">HONDA CONSERTO</option>
				<option value="ASCONA">ASCONA</option>
				<option value="DATSUN 120Y">DATSUN 120Y</option>
				<option value="TOYOTA LITEACE">TOYOTA LITEACE</option>
				<option value="KYMCO">KYMCO</option>
				<option value="TOYOTA PICK UP">TOYOTA PICK UP</option>
				<option value="V-WAGEN SATANNA">V-WAGEN SATANNA</option>
				<option value="PEUGEOT 405">PEUGEOT 405</option>
				<option value="CHERRY">CHERRY</option>
				<option value="MERCEDES-BENZ 320">MERCEDES-BENZ 320</option>
				<option value="HONDA HALLA">HONDA HALLA</option>
				<option value="FORD MONDEO">FORD MONDEO</option>
				<option value="FORD ESCORT">FORD ESCORT</option>
				<option value="VOLVO 244">VOLVO 244</option>
				<option value="DAEWOO RACER">DAEWOO RACER</option>
				<option value="VOLKS WAGEN POLO">VOLKS WAGEN POLO</option>
				<option value="TOYOTA AVENSIS">TOYOTA AVENSIS</option>
				<option value="KIA PICANTO">KIA PICANTO</option>
				<option value="NISSAN CENTRAL">NISSAN CENTRAL</option>
				<option value="RENAULT TWINGO">RENAULT TWINGO</option>
				<option value="RANGE ROVER JEEP">RANGE ROVER JEEP</option>
				<option value="HONDA CRV">HONDA CRV</option>
				<option value="MISTUBA">MISTUBA</option>
				<option value="B.M.W X 5">B.M.W X 5</option>
				<option value="XTERRA">XTERRA</option>
				<option value="NISSAN XTERRA">NISSAN XTERRA</option>
				<option value="TRUCK">TRUCK</option>
				<option value="SUZIKI SWIFT">SUZIKI SWIFT</option>
				<option value="FORD EXPLORER">FORD EXPLORER</option>
				<option value="WAGON">WAGON</option>
				<option value="DYNA">DYNA</option>
				<option value="FORD RANGER">FORD RANGER</option>
				<option value="VESPER">VESPER</option>
				<option value="DAYANG">DAYANG</option>
				<option value="AUDI 90">AUDI 90</option>
				<option value="ALTIMA">ALTIMA</option>
				<option value="MAZDA E2200">MAZDA E2200</option>
				<option value="BMW 3 SERIES">BMW 3 SERIES</option>
				<option value="IZUZU TROPPER">IZUZU TROPPER</option>
				<option value="MIT CANTER">MIT CANTER</option>
				<option value="TRONG">TRONG</option>
				<option value="TOYOTA HILUX">TOYOTA HILUX</option>
				<option value="NISSAN CABSTAR P/UP">NISSAN CABSTAR P/UP</option>
				<option value="MERCEDES-BENZ 300">MERCEDES-BENZ 300</option>
				<option value="V/WAGEN SANTANA">V/WAGEN SANTANA</option>
				<option value="LONCIN">LONCIN</option>
				<option value="TOYOTA CELICA">TOYOTA CELICA</option>
				<option value="DATSUN 180">DATSUN 180</option>
				<option value="BENZ ML">BENZ ML</option>
				<option value="VENUS">VENUS</option>
				<option value="VILLAGER MERCURY">VILLAGER MERCURY</option>
				<option value="STEYR">STEYR</option>
				<option value="CG 100 CARTER">CG 100 CARTER</option>
				<option value="V/BOOT">V/BOOT</option>
				<option value="MAZDA  PICK-UP">MAZDA  PICK-UP</option>
				<option value="HONDA LEGEND">HONDA LEGEND</option>
				<option value="STALLION">STALLION</option>
				<option value="MITSUBISHI PAJERO">MITSUBISHI PAJERO</option>
				<option value="DATSUN CHERRY">DATSUN CHERRY</option>
				<option value="PEUGEOT 305">PEUGEOT 305</option>
				<option value="FORD TRANSIT">FORD TRANSIT</option>
				<option value="TOYOTA  BUS">TOYOTA  BUS</option>
				<option value="DATSUN PANEL VAN">DATSUN PANEL VAN</option>
				<option value="PRIMERA">PRIMERA</option>
				<option value="PEUGEOT 605">PEUGEOT 605</option>
				<option value="MITSUBISHI MONTERO">MITSUBISHI MONTERO</option>
				<option value="CHERRY TIGGO">CHERRY TIGGO</option>
				<option value="HYUNDAI ACCENT">HYUNDAI ACCENT</option>
				<option value="V/GOLF">V/GOLF</option>
				<option value="MIT SPACE RUNNER">MIT SPACE RUNNER</option>
				<option value="OPEL ASCONA">OPEL ASCONA</option>
				<option value="M/BENZ E 200">M/BENZ E 200</option>
				<option value="M/BENZ E200">M/BENZ E200</option>
				<option value="DAF 2100">DAF 2100</option>
				<option value="EAGLE TALON">EAGLE TALON</option>
				<option value="MERCURY VILLAGE">MERCURY VILLAGE</option>
				<option value="TOYOTA CAMRY S/C">TOYOTA CAMRY S/C</option>
				<option value="VOLVO 940 S/CAR">VOLVO 940 S/CAR</option>
				<option value="NISSAN UD">NISSAN UD</option>
				<option value="PGT 504">PGT 504</option>
				<option value="M/BENZ C220">M/BENZ C220</option>
				<option value="MAZDA BUS">MAZDA BUS</option>
				<option value="STERLING SUNNY">STERLING SUNNY</option>
				<option value="FORD GOSWORTH">FORD GOSWORTH</option>
				<option value="M/BENZ 230">M/BENZ 230</option>
				<option value="X`S">X`S</option>
				<option value="MERCEDES-BENZ C220">MERCEDES-BENZ C220</option>
				<option value="GOLF 1">GOLF 1</option>
				<option value="TOYOTA CRESSIDA">TOYOTA CRESSIDA</option>
				<option value="SANTANA">SANTANA</option>
				<option value="PRIMERAL S/C">PRIMERAL S/C</option>
				<option value="DE-DAMAK">DE-DAMAK</option>
				<option value="VOLKS WAGEN PASSAT">VOLKS WAGEN PASSAT</option>
				<option value="VOLKSWAGEN BUS">VOLKSWAGEN BUS</option>
				<option value="CGL  125">CGL  125</option>
				<option value="HONDA CGL 125">HONDA CGL 125</option>
				<option value="NISSAN SERRENA">NISSAN SERRENA</option>
				<option value="NISSAN SERENA">NISSAN SERENA</option>
				<option value="TOYOTA COASTER">TOYOTA COASTER</option>
				<option value="AUDI 400">AUDI 400</option>
				<option value="VOLVO 440">VOLVO 440</option>
				<option value="ISUZU TROOPER">ISUZU TROOPER</option>
				<option value="TOYOTA TOWN ACE">TOYOTA TOWN ACE</option>
				<option value="VOLVO 240 GLT">VOLVO 240 GLT</option>
				<option value="M/DIESEL TRUCK">M/DIESEL TRUCK</option>
				<option value="MAN TRUCK">MAN TRUCK</option>
				<option value="JEEP PARTFINDER">JEEP PARTFINDER</option>
				<option value="VOLVO 240 GL">VOLVO 240 GL</option>
				<option value="V/WAGEN BETTLE">V/WAGEN BETTLE</option>
				<option value="DAEWOO  NUBIRA">DAEWOO  NUBIRA</option>
				<option value="NISSAN ARMADA JEEP">NISSAN ARMADA JEEP</option>
				<option value="PEUGEOT 404">PEUGEOT 404</option>
				<option value="M/BENZ DIESEL">M/BENZ DIESEL</option>
				<option value="OPEL SENATOR">OPEL SENATOR</option>
				<option value="B M W 520">B M W 520</option>
				<option value="SEPHIA II">SEPHIA II</option>
				<option value="BYD F3 GLX-I">BYD F3 GLX-I</option>
				<option value="OPEL FRONTERA">OPEL FRONTERA</option>
				<option value="ACURA LEGEND">ACURA LEGEND</option>
				<option value="HONDA DIANG">HONDA DIANG</option>
				<option value="NISSAN MINI BUS">NISSAN MINI BUS</option>
				<option value="SCANIA LORRY">SCANIA LORRY</option>
				<option value="TOYOTA PICNIC">TOYOTA PICNIC</option>
				<option value="FIAT CROMA">FIAT CROMA</option>
				<option value="MITSUBISHI CORROLA">MITSUBISHI CORROLA</option>
				<option value="HAISE">HAISE</option>
				<option value="CHERROLET AREOLT">CHERROLET AREOLT</option>
				<option value="VAUXHALL ESTATE">VAUXHALL ESTATE</option>
				<option value="SUBARU LEGACY">SUBARU LEGACY</option>
				<option value="MITSUBISHI STANCER">MITSUBISHI STANCER</option>
				<option value="MITSUBISHI SIGMA">MITSUBISHI SIGMA</option>
				<option value="FAKA MERCEDES">FAKA MERCEDES</option>
				<option value="NISSAN DATSUN">NISSAN DATSUN</option>
				<option value="VOLKWAGEN PARATI HL">VOLKWAGEN PARATI HL</option>
				<option value="CHEVROLET AVEO">CHEVROLET AVEO</option>
				<option value="MAZDA 2000">MAZDA 2000</option>
				<option value="MITSUBISHI LANCER">MITSUBISHI LANCER</option>
				<option value="HONDA PASSPORT">HONDA PASSPORT</option>
				<option value="VOLVO 960 S/C">VOLVO 960 S/C</option>
				<option value="SCANIA TRUCK">SCANIA TRUCK</option>
				<option value="ROVER 620">ROVER 620</option>
				<option value="FORD WINSTAR">FORD WINSTAR</option>
				<option value="PGT 505">PGT 505</option>
				<option value="DATSUN 160B">DATSUN 160B</option>
				<option value="GLS JEEP">GLS JEEP</option>
				<option value="GLS ">GLS </option>
				<option value="NISSAN CARBALL">NISSAN CARBALL</option>
				<option value="CRV">CRV</option>
				<option value="EURO TECH">EURO TECH</option>
				<option value="CHEVY VAN">CHEVY VAN</option>
				<option value="HONDA ACCENT">HONDA ACCENT</option>
				<option value="HONDA INTEGRA">HONDA INTEGRA</option>
				<option value="SUSAN">SUSAN</option>
				<option value="VOLVO 760">VOLVO 760</option>
				<option value="M/BENZ C240">M/BENZ C240</option>
				<option value="M/BENZ LORRY">M/BENZ LORRY</option>
				<option value="PEUGEOT 307">PEUGEOT 307</option>
				<option value="M/BENZ 190">M/BENZ 190</option>
				<option value="TROOPER JEEP">TROOPER JEEP</option>
				<option value="ML 320 JEEP">ML 320 JEEP</option>
				<option value="SCODA">SCODA</option>
				<option value="KIA OPTIMA">KIA OPTIMA</option>
				<option value="MERCEDES- BENZ 280">MERCEDES- BENZ 280</option>
				<option value="M/BENZ V/BOOT 230">M/BENZ V/BOOT 230</option>
				<option value="SUPERBIKE">SUPERBIKE</option>
				<option value="NISSAN PRARIE">NISSAN PRARIE</option>
				<option value="XINKAI">XINKAI</option>
				<option value="MERCEDES-BENZ V/BOOT">MERCEDES-BENZ V/BOOT</option>
				<option value="MERCEDES-BENZ V/BOOT 200">MERCEDES-BENZ V/BOOT 200</option>
				<option value="DATSUN PICK UP">DATSUN PICK UP</option>
				<option value="TATA VAN">TATA VAN</option>
				<option value="VOLVO 460">VOLVO 460</option>
				<option value="BENZ">BENZ</option>
				<option value="BMW 320">BMW 320</option>
				<option value="PEUGEOT TALBOT">PEUGEOT TALBOT</option>
				<option value="GOLF 3">GOLF 3</option>
				<option value="FRAGEND">FRAGEND</option>
				<option value="KINETIC WING">KINETIC WING</option>
				<option value="HONDA ODYSSEY">HONDA ODYSSEY</option>
				<option value="VOLVO 850">VOLVO 850</option>
				<option value="TOYOTA SEQVA">TOYOTA SEQVA</option>
				<option value="TOYOTA SEQUA">TOYOTA SEQUA</option>
				<option value="PICK- UP VAN">PICK- UP VAN</option>
				<option value="TOYOTA PANEL">TOYOTA PANEL</option>
				<option value="MERCEDES-BENZ 230 E">MERCEDES-BENZ 230 E</option>
				<option value="HAOJUE">HAOJUE</option>
				<option value="TEC MC">TEC MC</option>
				<option value="HONDA CRX">HONDA CRX</option>
				<option value="HYUNDAI SONATA">HYUNDAI SONATA</option>
				<option value="MERCEDES-BENZ 200E">MERCEDES-BENZ 200E</option>
				<option value="MERCEDES- BENZ E 200">MERCEDES- BENZ E 200</option>
				<option value="TEC MOTORCYCLE">TEC MOTORCYCLE</option>
				<option value="KIA BUS">KIA BUS</option>
				<option value="GOLF 3 STATION WAGON">GOLF 3 STATION WAGON</option>
				<option value="M/BENS 500">M/BENS 500</option>
				<option value="M/BENZ  S500">M/BENZ  S500</option>
				<option value="NISSAN JEEP">NISSAN JEEP</option>
				<option value="V/WAGEN BUS (MINI)">V/WAGEN BUS (MINI)</option>
				<option value="NISSAN INFINITY">NISSAN INFINITY</option>
				<option value="MERCEDES-BENZ C 200">MERCEDES-BENZ C 200</option>
				<option value="BEETTLE">BEETTLE</option>
				<option value="M/BENZ">M/BENZ</option>
				<option value="TOYOTA DYME P/UP">TOYOTA DYME P/UP</option>
				<option value="3SERIES">3SERIES</option>
				<option value="3SERIES1">3SERIES1</option>
				<option value="HONDA ACURA">HONDA ACURA</option>
				<option value="M/BENZ 180">M/BENZ 180</option>
				<option value="BEDFORD TIPPER LORRY">BEDFORD TIPPER LORRY</option>
				<option value="MIT TREDIA">MIT TREDIA</option>
				<option value="TOYOTA CONDOR">TOYOTA CONDOR</option>
				<option value="TOYOTA D/CUBIU">TOYOTA D/CUBIU</option>
				<option value="DOGER CARVAN">DOGER CARVAN</option>
				<option value="TOYOTA VENTURE">TOYOTA VENTURE</option>
				<option value="BMW 225">BMW 225</option>
				<option value="MERCEDES BENZ E 420">MERCEDES BENZ E 420</option>
				<option value="TOYOTA HILUS BUS">TOYOTA HILUS BUS</option>
				<option value="TOYOTA HILUX BUS">TOYOTA HILUX BUS</option>
				<option value="MITSUBISHI SAPPORO">MITSUBISHI SAPPORO</option>
				<option value="MERCEDES-BENZ E320">MERCEDES-BENZ E320</option>
				<option value="SUZUKI HAOJUE">SUZUKI HAOJUE</option>
				<option value="FORD ECONO">FORD ECONO</option>
				<option value="MERCEDES-BENZ 300 V/BOOT">MERCEDES-BENZ 300 V/BOOT</option>
				<option value="HYUNDAI TERRACAN">HYUNDAI TERRACAN</option>
				<option value="M/BENS 430">M/BENS 430</option>
				<option value="TERRACAN">TERRACAN</option>
				<option value="HYDUNAI JEEP">HYDUNAI JEEP</option>
				<option value="CHEVY 20">CHEVY 20</option>
				<option value="KIA SPORTAGE">KIA SPORTAGE</option>
				<option value="UNIT L200">UNIT L200</option>
				<option value="M/BENZ-PICKUP">M/BENZ-PICKUP</option>
				<option value="MAZ 626">MAZ 626</option>
				<option value="SUNNY">SUNNY</option>
				<option value="CHENGLONG BRAND DUMP">CHENGLONG BRAND DUMP</option>
				<option value="MITSUBISHI L200 PICK-UP VAN">MITSUBISHI L200 PICK-UP VAN</option>
				<option value="TOYOTA SUPRA">TOYOTA SUPRA</option>
				<option value="M/BENZ 260">M/BENZ 260</option>
				<option value="M/BENZ ML 350">M/BENZ ML 350</option>
				<option value="SANGYONG REXTON JEEP">SANGYONG REXTON JEEP</option>
				<option value="BMW 325 ">BMW 325 </option>
				<option value="FORD ESCOSPORT">FORD ESCOSPORT</option>
				<option value="GMC P/UP">GMC P/UP</option>
				<option value="HONDA PILOT">HONDA PILOT</option>
				<option value="MITSUBISHI ECLIPSE">MITSUBISHI ECLIPSE</option>
				<option value="MERCEDES-BENZ E230">MERCEDES-BENZ E230</option>
				<option value="M/BENZ S550">M/BENZ S550</option>
				<option value="AURORA JEEP">AURORA JEEP</option>
				<option value="M/BENZ C CLASS">M/BENZ C CLASS</option>
				<option value="OPEL SANITRA">OPEL SANITRA</option>
				<option value="DODGE CARAVAN">DODGE CARAVAN</option>
				<option value="FORD TAURUS">FORD TAURUS</option>
				<option value="TATA TRUCK">TATA TRUCK</option>
				<option value="LADA NIVA">LADA NIVA</option>
				<option value="GMC JEEP">GMC JEEP</option>
				<option value="TEC SPEED 2">TEC SPEED 2</option>
				<option value="MAZDA XEDOS">MAZDA XEDOS</option>
				<option value="TOYOTA CROWN">TOYOTA CROWN</option>
				<option value="MUDAN P/UP">MUDAN P/UP</option>
				<option value="MITSUBISHI JEEP">MITSUBISHI JEEP</option>
				<option value="SKODA FABIA">SKODA FABIA</option>
				<option value="OPEL RECORD">OPEL RECORD</option>
				<option value="CHEVROLET OPTRA">CHEVROLET OPTRA</option>
				<option value="BMW 535">BMW 535</option>
				<option value="V/WAGEN VENTO">V/WAGEN VENTO</option>
				<option value="KIA BESTA">KIA BESTA</option>
				<option value="CHERY COWIN">CHERY COWIN</option>
				<option value="ECONOVAN">ECONOVAN</option>
				<option value="MBENZ 120">MBENZ 120</option>
				<option value="FORD CARGO">FORD CARGO</option>
				<option value="M/BENZ 120">M/BENZ 120</option>
				<option value="JINBEI HAISE">JINBEI HAISE</option>
				<option value="DAEWOO PRINCE 4">DAEWOO PRINCE 4</option>
				<option value="PEUGEOT 407">PEUGEOT 407</option>
				<option value="NANFANG AX100">NANFANG AX100</option>
				<option value="NISSAN S/CAR">NISSAN S/CAR</option>
				<option value="NISSAN SINVA">NISSAN SINVA</option>
				<option value="TIGER QUINIK">TIGER QUINIK</option>
				<option value="STYER">STYER</option>
				<option value="MIT TREDIS">MIT TREDIS</option>
				<option value="CIVILLIAN BUS">CIVILLIAN BUS</option>
				<option value="TOYOTA L/BACK">TOYOTA L/BACK</option>
				<option value="MAZDA 929">MAZDA 929</option>
				<option value="TOYOTA MODEL F">TOYOTA MODEL F</option>
				<option value="LADA">LADA</option>
				<option value="ARMOURED CASH CARRIER">ARMOURED CASH CARRIER</option>
				<option value="DAIHATSU CHARMANT">DAIHATSU CHARMANT</option>
				<option value="MERCEDES-BENZ 190 E">MERCEDES-BENZ 190 E</option>
				<option value="MERCEDES-BENZ 230E V/BOOT">MERCEDES-BENZ 230E V/BOOT</option>
				<option value="NISSAN MECURY">NISSAN MECURY</option>
				<option value="NISSAN 100 NX">NISSAN 100 NX</option>
				<option value="PEUGEOT 206">PEUGEOT 206</option>
				<option value="KIA SEDOINA">KIA SEDOINA</option>
				<option value="PEUGEOT 607">PEUGEOT 607</option>
				<option value="MACK TRUCK">MACK TRUCK</option>
				<option value="MAZDA E2000">MAZDA E2000</option>
				<option value="TEC">TEC</option>
				<option value="LEBAO JEEP">LEBAO JEEP</option>
				<option value="HAOJUE SUZUKI">HAOJUE SUZUKI</option>
				<option value="LEYLAND DAF">LEYLAND DAF</option>
				<option value="ERF-EC11">ERF-EC11</option>
				<option value="TOYOTA ECHO">TOYOTA ECHO</option>
				<option value="M/BENZ C 280">M/BENZ C 280</option>
				<option value="CHANGFENG">CHANGFENG</option>
				<option value="HYUNDAI SANTAFE">HYUNDAI SANTAFE</option>
				<option value="ISUZU RODEO">ISUZU RODEO</option>
				<option value="BMW 525">BMW 525</option>
				<option value="SEAT IBIZA">SEAT IBIZA</option>
				<option value="CARGO">CARGO</option>
				<option value="VOLVO 240 SPACE WAGON">VOLVO 240 SPACE WAGON</option>
				<option value="NEXIA DAEWOO">NEXIA DAEWOO</option>
				<option value="DATSUN 240 ">DATSUN 240 </option>
				<option value="HYUNDAI PONY">HYUNDAI PONY</option>
				<option value="CROSS EASTER V5">CROSS EASTER V5</option>
				<option value="NISSAN DIESEL TIPPER">NISSAN DIESEL TIPPER</option>
				<option value="AUDI  A4">AUDI  A4</option>
				<option value="DAYLONG">DAYLONG</option>
				<option value="HONDA JAZZ">HONDA JAZZ</option>
				<option value="BABY STARLET">BABY STARLET</option>
				<option value="STALLON">STALLON</option>
				<option value="MARUTI  S/CAR">MARUTI  S/CAR</option>
				<option value="M/BENZ 230 E">M/BENZ 230 E</option>
				<option value="T.V.S STAR">T.V.S STAR</option>
				<option value="S/WAGON BLUE-BIRD">S/WAGON BLUE-BIRD</option>
				<option value="B/BIRD S/WAGON">B/BIRD S/WAGON</option>
				<option value="TOYOTA HIGHLANDER">TOYOTA HIGHLANDER</option>
				<option value="M/BENZ 210">M/BENZ 210</option>
				<option value="TOYOTA  CARINA 11">TOYOTA  CARINA 11</option>
				<option value="ACURA  MDX">ACURA  MDX</option>
				<option value="DAMLER">DAMLER</option>
				<option value="MERCEDES-BENZ 500">MERCEDES-BENZ 500</option>
				<option value="CHEVROLET  LUMINA">CHEVROLET  LUMINA</option>
				<option value="TOYOTA YARIS">TOYOTA YARIS</option>
				<option value="LINCON NAVIGATOR">LINCON NAVIGATOR</option>
				<option value="M/BENZ 190E">M/BENZ 190E</option>
				<option value="VOLVO 264">VOLVO 264</option>
				<option value="MERCEDES-BENZ ML 350">MERCEDES-BENZ ML 350</option>
				<option value="DAIHATSU APPLUSE">DAIHATSU APPLUSE</option>
				<option value="GALLOPE">GALLOPE</option>
				<option value="GRAND JEEP">GRAND JEEP</option>
				<option value="B M W">B M W</option>
				<option value="M/BENZ 250E">M/BENZ 250E</option>
				<option value="CHERRY QQ6">CHERRY QQ6</option>
				<option value="TIAMA JEEP">TIAMA JEEP</option>
				<option value="SONATA">SONATA</option>
				<option value="JEEP 4 RUNNER">JEEP 4 RUNNER</option>
				<option value="TOYOTA CORONA">TOYOTA CORONA</option>
				<option value="MERCEDES-BENZ SLK 350">MERCEDES-BENZ SLK 350</option>
				<option value="MAXI-TRICYCLE">MAXI-TRICYCLE</option>
				<option value="NISSAN KING CAB">NISSAN KING CAB</option>
				<option value="MITSIBUSHI L400">MITSIBUSHI L400</option>
				<option value="M/BENZ C260">M/BENZ C260</option>
				<option value="PEUGEOT 205">PEUGEOT 205</option>
				<option value="MRECEDES-BENZ 280">MRECEDES-BENZ 280</option>
				<option value="MERCEDES-BENZ 280">MERCEDES-BENZ 280</option>
				<option value="M/BENZ BUS">M/BENZ BUS</option>
				<option value="MERCEDES-BENZ 1417">MERCEDES-BENZ 1417</option>
				<option value="NISSAN XTRAIL">NISSAN XTRAIL</option>
				<option value="BMW X3">BMW X3</option>
				<option value="LADA JEEP">LADA JEEP</option>
				<option value="LAND CRUISER">LAND CRUISER</option>
				<option value="OPTIMAL KIA">OPTIMAL KIA</option>
				<option value="DATSUN VIOLET">DATSUN VIOLET</option>
				<option value="V/WAGEN">V/WAGEN</option>
				<option value="M/BENZ 711 BUS">M/BENZ 711 BUS</option>
				<option value="TOYOTA PREVIER">TOYOTA PREVIER</option>
				<option value="INTERNATIONAL">INTERNATIONAL</option>
				<option value="MITS L300">MITS L300</option>
				<option value="MERRIS TIPPER">MERRIS TIPPER</option>
				<option value="BERLIET">BERLIET</option>
				<option value="VOLVO 744">VOLVO 744</option>
				<option value="THILUX PICK UP">THILUX PICK UP</option>
				<option value="THILUX">THILUX</option>
				<option value="HONDA SHUTTLE">HONDA SHUTTLE</option>
				<option value="LEYLAND TIMBER LORRY">LEYLAND TIMBER LORRY</option>
				<option value="LANTRA">LANTRA</option>
				<option value="MERCEDES-BENZ S CLASS">MERCEDES-BENZ S CLASS</option>
				<option value="VOLKSWAGEN LT 35 BUS">VOLKSWAGEN LT 35 BUS</option>
				<option value="MAZDA 327">MAZDA 327</option>
				<option value="DATSUN 140">DATSUN 140</option>
				<option value="VOLKSWAGEN BORA">VOLKSWAGEN BORA</option>
				<option value="BMW 5201">BMW 5201</option>
				<option value="FORD VILLAGER">FORD VILLAGER</option>
				<option value="FREIGHT LINER">FREIGHT LINER</option>
				<option value="DAF VAN">DAF VAN</option>
				<option value="TOYATA TUNDRA">TOYATA TUNDRA</option>
				<option value="TOYOTA TUNDRA">TOYOTA TUNDRA</option>
				<option value="MERCEDES BENZ 407">MERCEDES BENZ 407</option>
				<option value="PAJERO DIESEL">PAJERO DIESEL</option>
				<option value="BAJAJ  BOXERS">BAJAJ  BOXERS</option>
				<option value="OPEL WAGON">OPEL WAGON</option>
				<option value="V/WAGEN GOLF">V/WAGEN GOLF</option>
				<option value="M/BENZ 320 E CLASS">M/BENZ 320 E CLASS</option>
				<option value="DATSUN JEEP">DATSUN JEEP</option>
				<option value="B M W 320">B M W 320</option>
				<option value="BEDFORD/TIPP/LORRY">BEDFORD/TIPP/LORRY</option>
				<option value="FORD EXPEDITION">FORD EXPEDITION</option>
				<option value="DAF 1900">DAF 1900</option>
				<option value="LIBRADO">LIBRADO</option>
				<option value="MERCEDES BENZ E430">MERCEDES BENZ E430</option>
				<option value="KEWESEKI">KEWESEKI</option>
				<option value="VANXHALL ZAFIRA">VANXHALL ZAFIRA</option>
				<option value="STRONG">STRONG</option>
				<option value="HONDA BOLLET SALOON CAR">HONDA BOLLET SALOON CAR</option>
				<option value="HONDA BULLET SALOON CAR">HONDA BULLET SALOON CAR</option>
				<option value="ISUZU MIDI">ISUZU MIDI</option>
				<option value="ASTRA">ASTRA</option>
				<option value="ASTRA OPEL">ASTRA OPEL</option>
				<option value="V/W BORA">V/W BORA</option>
				<option value="BORA">BORA</option>
				<option value="M/BENZ  MINI BUS">M/BENZ  MINI BUS</option>
				<option value="K50">K50</option>
				<option value="PULSAR">PULSAR</option>
				<option value="KIA SEPHIA">KIA SEPHIA</option>
				<option value="ISUZU RODES">ISUZU RODES</option>
				<option value="KIA SORENTO">KIA SORENTO</option>
				<option value="MORES LORRY">MORES LORRY</option>
				<option value="SCOVIO">SCOVIO</option>
				<option value="CHYSLER STRATUS">CHYSLER STRATUS</option>
				<option value="VANETTE BUS">VANETTE BUS</option>
				<option value="MINI LDV ">MINI LDV </option>
				<option value="V/WAGEN BUS">V/WAGEN BUS</option>
				<option value="DAF 400">DAF 400</option>
				<option value="PEUGEOT 204">PEUGEOT 204</option>
				<option value="CAPENTER">CAPENTER</option>
				<option value="URVAN BUS">URVAN BUS</option>
				<option value="MERCEDES-BENZE280">MERCEDES-BENZE280</option>
				<option value="URVAN">URVAN</option>
				<option value="MITSUBISHI CANTER">MITSUBISHI CANTER</option>
				<option value="NISSAN TRUCK">NISSAN TRUCK</option>
				<option value="TOYOTA SHAMANT">TOYOTA SHAMANT</option>
				<option value="CHANGAN">CHANGAN</option>
				<option value="SKY TIPPER">SKY TIPPER</option>
				<option value="M/BENZ 800">M/BENZ 800</option>
				<option value="IVECO FIAT SPA">IVECO FIAT SPA</option>
				<option value="FREELANDER">FREELANDER</option>
				<option value="TOYOTA DELUXE">TOYOTA DELUXE</option>
				<option value="NISSAN 120Y">NISSAN 120Y</option>
				<option value="MORRIS TANKER">MORRIS TANKER</option>
				<option value="PONTIAC TRANSPORT">PONTIAC TRANSPORT</option>
				<option value="LEXUS 330">LEXUS 330</option>
				<option value="TOYOTA QUEST">TOYOTA QUEST</option>
				<option value="TRI-CYCLE">TRI-CYCLE</option>
				<option value="M/BENZ R500">M/BENZ R500</option>
				<option value="PEUGEOT J5">PEUGEOT J5</option>
				<option value="MIT SPACE WAGON">MIT SPACE WAGON</option>
				<option value="FIAT PICK UP">FIAT PICK UP</option>
				<option value="ISUZU TRANSPORTER">ISUZU TRANSPORTER</option>
				<option value="MUNDIO FORD">MUNDIO FORD</option>
				<option value="HYUNDAI ELENTRA">HYUNDAI ELENTRA</option>
				<option value="HONDA HALLER">HONDA HALLER</option>
				<option value="HONDA CIVIC LIFT BACK">HONDA CIVIC LIFT BACK</option>
				<option value="NISSAN CABSTER">NISSAN CABSTER</option>
				<option value="COMMANDER">COMMANDER</option>
				<option value="GRAND CHEROKE">GRAND CHEROKE</option>
				<option value="HIAB">HIAB</option>
				<option value="NISSAN PRAURE">NISSAN PRAURE</option>
				<option value="LEYLAND MASTER">LEYLAND MASTER</option>
				<option value="MIT L 200">MIT L 200</option>
				<option value="LIEBAO ">LIEBAO </option>
				<option value="M/BENZ 200">M/BENZ 200</option>
				<option value="ZION CG 125">ZION CG 125</option>
				<option value="M/BENZ 608 LORRY">M/BENZ 608 LORRY</option>
				<option value="INT SCH .BUS">INT SCH .BUS</option>
				<option value="MERCEDES BENZ TRUCK">MERCEDES BENZ TRUCK</option>
				<option value="MERCEDES-BENZ TRUCK">MERCEDES-BENZ TRUCK</option>
				<option value="DAIHATSU CHARADE">DAIHATSU CHARADE</option>
				<option value="CNHTC STEYR">CNHTC STEYR</option>
				<option value="MERCEDES-BENZ 260">MERCEDES-BENZ 260</option>
				<option value="V/W JETTA">V/W JETTA</option>
				<option value="M/BENS 300 V/BOOT">M/BENS 300 V/BOOT</option>
				<option value="MAZDA MILLENIA">MAZDA MILLENIA</option>
				<option value="M/BENZ C180">M/BENZ C180</option>
				<option value="BMW SERIES 3">BMW SERIES 3</option>
				<option value="MERCEDES-BENZ E 220">MERCEDES-BENZ E 220</option>
				<option value="SCORPIO">SCORPIO</option>
				<option value="KIA CARENS">KIA CARENS</option>
				<option value="RACER DAEWOO">RACER DAEWOO</option>
				<option value="MITSUBA ">MITSUBA </option>
				<option value="B MW 750">B MW 750</option>
				<option value="FORD IVECO">FORD IVECO</option>
				<option value="M/ BENZ 307 ">M/ BENZ 307 </option>
				<option value="VIRT 4 TRANSPORTER ">VIRT 4 TRANSPORTER </option>
				<option value="DAIHAES PICK UP">DAIHAES PICK UP</option>
				<option value="MOT SPACE WAGON">MOT SPACE WAGON</option>
				<option value="ZUZAIN">ZUZAIN</option>
				<option value="KYM EAGLED">KYM EAGLED</option>
				<option value="PLASMA">PLASMA</option>
				<option value="FOTON P/UP">FOTON P/UP</option>
				<option value="LT 28 ">LT 28 </option>
				<option value="FORD SERIES">FORD SERIES</option>
				<option value="HYUNDAI STELLA">HYUNDAI STELLA</option>
				<option value="MITSUBISHI DIAMANTE">MITSUBISHI DIAMANTE</option>
				<option value="NISSAN HOMO">NISSAN HOMO</option>
				<option value="TOYOTA SEQUIOA">TOYOTA SEQUIOA</option>
				<option value="CANTER">CANTER</option>
				<option value="VOLVO 940">VOLVO 940</option>
				<option value="MAZDA MPV">MAZDA MPV</option>
				<option value="NISSAN VAN">NISSAN VAN</option>
				<option value="MERCEDES-BENZ 2000">MERCEDES-BENZ 2000</option>
				<option value="OMGO 90">OMGO 90</option>
				<option value="NEW  TVS STAR">NEW  TVS STAR</option>
				<option value="B.M.W.325">B.M.W.325</option>
				<option value="IVECO FIAT">IVECO FIAT</option>
				<option value="M/BENZ E240">M/BENZ E240</option>
				<option value="RAM WAGON">RAM WAGON</option>
				<option value="ISUZU TIGER">ISUZU TIGER</option>
				<option value="NEON">NEON</option>
				<option value="LIFAN CG 125">LIFAN CG 125</option>
				<option value="H1 M/BUS">H1 M/BUS</option>
				<option value="P/UP">P/UP</option>
				<option value="NISSAN PREPRAIR">NISSAN PREPRAIR</option>
				<option value="TOW">TOW</option>
				<option value="PASSAT GL">PASSAT GL</option>
				<option value="ROVER 820">ROVER 820</option>
				<option value="MAZDA E1600">MAZDA E1600</option>
				<option value="M/BENZ ML 320">M/BENZ ML 320</option>
				<option value="TOYOTA WAGON">TOYOTA WAGON</option>
				<option value="MIT CARISNA">MIT CARISNA</option>
				<option value="NISSAN SILVIA">NISSAN SILVIA</option>
				<option value="CASH">CASH</option>
				<option value="LICON">LICON</option>
				<option value="XSTRONG">XSTRONG</option>
				<option value="TOWN ACE">TOWN ACE</option>
				<option value="IVECO TIPPING">IVECO TIPPING</option>
				<option value="LANXIANG">LANXIANG</option>
				<option value="TOYOTA PRIZM">TOYOTA PRIZM</option>
				<option value="INNOSON">INNOSON</option>
				<option value="INNOSON CGL125">INNOSON CGL125</option>
				<option value="BMW 318">BMW 318</option>
				<option value="NISSAN MICRAL">NISSAN MICRAL</option>
				<option value="HONDA ACURA LEGEND">HONDA ACURA LEGEND</option>
				<option value="HYUNDAI LANCER">HYUNDAI LANCER</option>
				<option value="ROVER 600">ROVER 600</option>
				<option value="ASIA BUS">ASIA BUS</option>
				<option value="PAJERO JEEP">PAJERO JEEP</option>
				<option value="PAJERO">PAJERO</option>
				<option value="MHSUBA AX100">MHSUBA AX100</option>
				<option value="ODDYSSEY">ODDYSSEY</option>
				<option value="KEKE NAPEP">KEKE NAPEP</option>
				<option value="DATSUN TRAVELLER">DATSUN TRAVELLER</option>
				<option value="NISSAN PRIARIE">NISSAN PRIARIE</option>
				<option value="TOYOTA SEQUOLA JEEP">TOYOTA SEQUOLA JEEP</option>
				<option value="MERCURY VILLAGER">MERCURY VILLAGER</option>
				<option value="CHRYSLER SARATOGA">CHRYSLER SARATOGA</option>
				<option value="MIT CARISMA">MIT CARISMA</option>
				<option value="DATSUN VAN">DATSUN VAN</option>
				<option value="CHEVY VENTIRE">CHEVY VENTIRE</option>
				<option value="VOLVO 745">VOLVO 745</option>
				<option value="TIMBER TRUCK">TIMBER TRUCK</option>
				<option value="HYUNDAI HIDO">HYUNDAI HIDO</option>
				<option value="TRACTOR FT704">TRACTOR FT704</option>
				<option value="MERCEDES-BENZ 280S">MERCEDES-BENZ 280S</option>
				<option value="BONGO">BONGO</option>
				<option value="HILUS P/UP">HILUS P/UP</option>
				<option value="MITSUBISHI SAPPIRO">MITSUBISHI SAPPIRO</option>
				<option value="FORD VAN">FORD VAN</option>
				<option value="MERCEDES-BENZ 350">MERCEDES-BENZ 350</option>
				<option value="NISSAN VIOLET">NISSAN VIOLET</option>
				<option value="BAJAJ TRICYCLE">BAJAJ TRICYCLE</option>
				<option value="MPI  LBLP GLS">MPI  LBLP GLS</option>
				<option value="NISSAN SIENNA">NISSAN SIENNA</option>
				<option value="LIBERTY JEEP">LIBERTY JEEP</option>
				<option value="PETERBILT">PETERBILT</option>
				<option value="PARAGON PICK UP">PARAGON PICK UP</option>
				<option value="SERENA BUS">SERENA BUS</option>
				<option value="ZINBA GL">ZINBA GL</option>
				<option value="TIPPER">TIPPER</option>
				<option value="TOYOTA JEEP LIMITED">TOYOTA JEEP LIMITED</option>
				<option value="VOLVO 244 GL">VOLVO 244 GL</option>
				<option value="MITSUBISHI EAGLE SUMMIT">MITSUBISHI EAGLE SUMMIT</option>
				<option value="NEXUS">NEXUS</option>
				<option value="M/BENZ 207 BUS">M/BENZ 207 BUS</option>
				<option value="OCTAVIA">OCTAVIA</option>
				<option value="VOLKSWAGEN OCTAVIA">VOLKSWAGEN OCTAVIA</option>
				<option value="DAF 85 TRUCK">DAF 85 TRUCK</option>
				<option value="DAF TRUCK">DAF TRUCK</option>
				<option value="HONDA JEEP">HONDA JEEP</option>
				<option value="CHEVROLET CAPRICE">CHEVROLET CAPRICE</option>
				<option value="RENAULT EXPRESS">RENAULT EXPRESS</option>
				<option value="M/BENZ 308">M/BENZ 308</option>
				<option value="AUSTIC DIESEL">AUSTIC DIESEL</option>
				<option value="MITSUBISHI L310">MITSUBISHI L310</option>
				<option value="M/BENZ S 500">M/BENZ S 500</option>
				<option value="AVEO LT">AVEO LT</option>
				<option value="TOYOTA JEEP">TOYOTA JEEP</option>
				<option value="PRIMERA INFINITY">PRIMERA INFINITY</option>
				<option value="IVECO 100">IVECO 100</option>
				<option value="BYD F3 GLI">BYD F3 GLI</option>
				<option value="ISUZU OASIS">ISUZU OASIS</option>
				<option value="FAIHO PICK-UP">FAIHO PICK-UP</option>
				<option value="V/WAGEN AUDI 80">V/WAGEN AUDI 80</option>
				<option value="FORK LIFT">FORK LIFT</option>
				<option value="TOYOTA RUNNER">TOYOTA RUNNER</option>
				<option value="KOMBUS">KOMBUS</option>
				<option value="MERCEDES">MERCEDES</option>
				<option value="--">--</option>
				<option value="VENTO JETTA">VENTO JETTA</option>
				<option value="PARAGON BUS">PARAGON BUS</option>
				<option value="SSANG YOUNG MUSSO">SSANG YOUNG MUSSO</option>
				<option value="M/BENZ 230TE">M/BENZ 230TE</option>
				<option value="FODEN">FODEN</option>
				<option value="FODEN 2235">FODEN 2235</option>
				<option value="DATSUN MAXIMA">DATSUN MAXIMA</option>
				<option value="DATSUN VANNETTE BUS">DATSUN VANNETTE BUS</option>
				<option value="M/B TIPPER">M/B TIPPER</option>
				<option value="M/BENZ 1317">M/BENZ 1317</option>
				<option value="VOLVO S40">VOLVO S40</option>
				<option value="FORD SCOPIO">FORD SCOPIO</option>
				<option value="M/BENZ P/UP">M/BENZ P/UP</option>
				<option value="M/BENZ S 420">M/BENZ S 420</option>
				<option value="M/BENZ 280 SE">M/BENZ 280 SE</option>
				<option value="NISSAN LORRY">NISSAN LORRY</option>
				<option value="MAZDA B2300">MAZDA B2300</option>
				<option value="DAKOTA ">DAKOTA </option>
				<option value="FIAT DUCATO BUS">FIAT DUCATO BUS</option>
				<option value="JINCHENG AX100">JINCHENG AX100</option>
				<option value="AUSTIN LORRY">AUSTIN LORRY</option>
				<option value="MAZDA B2000">MAZDA B2000</option>
				<option value="CHIROKE JEEP">CHIROKE JEEP</option>
				<option value="PANEL VAN">PANEL VAN</option>
				<option value="PANEL">PANEL</option>
				<option value="GL P/VAN">GL P/VAN</option>
				<option value="FOLDEN TIPPING ">FOLDEN TIPPING </option>
				<option value="LIMOSINE CARDILAC">LIMOSINE CARDILAC</option>
				<option value="TOYOTA TACOMA">TOYOTA TACOMA</option>
				<option value="MAZDA 121">MAZDA 121</option>
				<option value="PAC-LAW">PAC-LAW</option>
				<option value="INFINITY QX4">INFINITY QX4</option>
				<option value="CG 125">CG 125</option>
				<option value="ERF">ERF</option>
				<option value="M/BENZ C-220">M/BENZ C-220</option>
				<option value="BORA PASSAT">BORA PASSAT</option>
				<option value="ABRO C CGL 125">ABRO C CGL 125</option>
				<option value="ABRO M OTOR-CYCLE">ABRO M OTOR-CYCLE</option>
				<option value="M/BENZ E280">M/BENZ E280</option>
				<option value="DATSUN 200L">DATSUN 200L</option>
				<option value="V / WAGEN JETTA S / C">V / WAGEN JETTA S / C</option>
				<option value="MERCEDES-BENZ C180">MERCEDES-BENZ C180</option>
				<option value="CHERRY A520">CHERRY A520</option>
				<option value="FABIA">FABIA</option>
				<option value="FRAND CG125">FRAND CG125</option>
				<option value="S/WAGON">S/WAGON</option>
				<option value="LEADER">LEADER</option>
				<option value="DALONG">DALONG</option>
				<option value="COASTER BUS">COASTER BUS</option>
				<option value="VOLVO S90">VOLVO S90</option>
				<option value="GOLDEN DRAGON BUSES">GOLDEN DRAGON BUSES</option>
				<option value="NISSAN C20">NISSAN C20</option>
				<option value="KIA CERATO">KIA CERATO</option>
				<option value="MERCEDES-BENZ 220">MERCEDES-BENZ 220</option>
				<option value="M/BENZ 220">M/BENZ 220</option>
				<option value="HONDA BULLDOG">HONDA BULLDOG</option>
				<option value="LINCON">LINCON</option>
				<option value="FOTON TRUCK">FOTON TRUCK</option>
				<option value="WECO TRUCK">WECO TRUCK</option>
				<option value="EXPERT VAN">EXPERT VAN</option>
				<option value="LONAN">LONAN</option>
				<option value="BEDFORD LORRY">BEDFORD LORRY</option>
				<option value="RENAULT SAFRANE">RENAULT SAFRANE</option>
				<option value="M/BENZ 100">M/BENZ 100</option>
				<option value="CY 80">CY 80</option>
				<option value="CONCORD">CONCORD</option>
				<option value="FOTON">FOTON</option>
				<option value="M/BENZ 280S">M/BENZ 280S</option>
				<option value="HIACE BUS">HIACE BUS</option>
				<option value="NISSAN TERRAN">NISSAN TERRAN</option>
				<option value="TOYOTA DX">TOYOTA DX</option>
				<option value="D/FENG TRUCK">D/FENG TRUCK</option>
				<option value="WISSEN">WISSEN</option>
				<option value="FIAT       682TS">FIAT       682TS</option>
				<option value="SIERRA FORD">SIERRA FORD</option>
				<option value="KENWORTH TRUCK">KENWORTH TRUCK</option>
				<option value="AX100">AX100</option>
				<option value="M/BENZ C CLASS 200">M/BENZ C CLASS 200</option>
				<option value="NEW HOLLAND">NEW HOLLAND</option>
				<option value="SHINEBLUG">SHINEBLUG</option>
				<option value="WESTERN STAR">WESTERN STAR</option>
				<option value="ROYAL M/C">ROYAL M/C</option>
				<option value="MULTIVAN BUS">MULTIVAN BUS</option>
				<option value="FIAT TIPO">FIAT TIPO</option>
				<option value="NIPON">NIPON</option>
				<option value="NISSAN LANCER">NISSAN LANCER</option>
				<option value="ISTANA">ISTANA</option>
				<option value="JETTA EXECUTIVE">JETTA EXECUTIVE</option>
				<option value="TRICYCLE">TRICYCLE</option>
				<option value="AERONAUTIC">AERONAUTIC</option>
				<option value="SAFE JEEP">SAFE JEEP</option>
				<option value="NISSAN EBRO">NISSAN EBRO</option>
				<option value="FORD COURIER">FORD COURIER</option>
				<option value="MAZDA E200">MAZDA E200</option>
				<option value="DFL">DFL</option>
				<option value="INFINITT CAR">INFINITT CAR</option>
				<option value="MITSUBISHI EXPO">MITSUBISHI EXPO</option>
				<option value="FORD RANIT">FORD RANIT</option>
				<option value="TOYOTA 4RUNNER">TOYOTA 4RUNNER</option>
				<option value="SUPER M/CYCLE">SUPER M/CYCLE</option>
				<option value="FIAT FIORINO">FIAT FIORINO</option>
				<option value="M/BENZ 300 E">M/BENZ 300 E</option>
				<option value="LUXURIUS BUS">LUXURIUS BUS</option>
				<option value="MARCOPOLLO">MARCOPOLLO</option>
				<option value="COFRIER">COFRIER</option>
				<option value="HINO TIPPER">HINO TIPPER</option>
				<option value="TRADIA">TRADIA</option>
				<option value="MITSUBISHI TRADIA">MITSUBISHI TRADIA</option>
				<option value="SEDO ATKING">SEDO ATKING</option>
				<option value="DATSUN 1600">DATSUN 1600</option>
				<option value="TOYOTA SEQUIA">TOYOTA SEQUIA</option>
				<option value="HONDA CR-U">HONDA CR-U</option>
				<option value="FOTON VIEW">FOTON VIEW</option>
				<option value="SEAT CORDOBA">SEAT CORDOBA</option>
				<option value="KASS BOHOER">KASS BOHOER</option>
				<option value="KVMCO M/C">KVMCO M/C</option>
				<option value="VOLVO940GL">VOLVO940GL</option>
				<option value="VOLVO 940GL">VOLVO 940GL</option>
				<option value="CHRYSER">CHRYSER</option>
				<option value="ESPERO">ESPERO</option>
				<option value="MITSUBISHI DOUBLE CABIN">MITSUBISHI DOUBLE CABIN</option>
				<option value="CASH VAN">CASH VAN</option>
				<option value="TOYOTA COMPACT">TOYOTA COMPACT</option>
				<option value="DAEWOO LENOS">DAEWOO LENOS</option>
				<option value="MAZDA PROTEGE">MAZDA PROTEGE</option>
				<option value="SUZUKI AX 100">SUZUKI AX 100</option>
				<option value="SUZUKI SWIFT">SUZUKI SWIFT</option>
				<option value="OPTIMA ">OPTIMA </option>
				<option value="DAIRLAR JEEP">DAIRLAR JEEP</option>
				<option value="VOLVO 740 GL">VOLVO 740 GL</option>
				<option value="ISUZU VAN">ISUZU VAN</option>
				<option value="MAZDA B2500">MAZDA B2500</option>
				<option value="M/BENZ ML500">M/BENZ ML500</option>
				<option value="DAKOTA CG 125">DAKOTA CG 125</option>
				<option value="GOLD CROWN">GOLD CROWN</option>
				<option value="SKY JET">SKY JET</option>
				<option value="DISCOVERY JEEP">DISCOVERY JEEP</option>
				<option value="PEUGEOT 406 S/WAGON">PEUGEOT 406 S/WAGON</option>
				<option value="V/WAGEN POLO">V/WAGEN POLO</option>
				<option value="PORCHE">PORCHE</option>
				<option value="PICANTO KIA">PICANTO KIA</option>
				<option value="GOLDEN DRAGON BUS">GOLDEN DRAGON BUS</option>
				<option value="DODGE RAM">DODGE RAM</option>
				<option value="NAPEP BAGGIO">NAPEP BAGGIO</option>
				<option value="REGAL">REGAL</option>
				<option value="REGALS">REGALS</option>
				<option value="MIT GALLANT">MIT GALLANT</option>
				<option value="SUZUKI BALENO S/C">SUZUKI BALENO S/C</option>
				<option value="TOYOTA CARINA S/CAR">TOYOTA CARINA S/CAR</option>
				<option value="QUEST">QUEST</option>
				<option value="CHEVROLET BLAZER">CHEVROLET BLAZER</option>
				<option value="V/WAGEN LT 28 BUS">V/WAGEN LT 28 BUS</option>
				<option value="CIVIC 1.7 VTISE">CIVIC 1.7 VTISE</option>
				<option value="MIT OUTLANDER">MIT OUTLANDER</option>
				<option value="ELANTRA">ELANTRA</option>
				<option value="NISSAN TIIDA">NISSAN TIIDA</option>
				<option value="VOLVO S80">VOLVO S80</option>
				<option value="1617">1617</option>

				<option value="TOYOTA VANNETTE">TOYOTA VANNETTE</option>
				<option value="DAF 45 TRUCK">DAF 45 TRUCK</option>
				<option value="LAUREL">LAUREL</option>
				<option value="N/C123">N/C123</option>
				<option value="VOLVO BUS">VOLVO BUS</option>
				<option value="NIPPO SUPRA">NIPPO SUPRA</option>
				<option value="NIPPON SUPRA">NIPPON SUPRA</option>
				<option value="VOLVO B10M70">VOLVO B10M70</option>
				<option value="ACCENT">ACCENT</option>
				<option value="LIFT BACK">LIFT BACK</option>
				<option value="GREAT WALL DEER">GREAT WALL DEER</option>
				<option value="GALLARD">GALLARD</option>
				<option value="OPEL/ASTRA">OPEL/ASTRA</option>
				<option value="M/BENZ ML300">M/BENZ ML300</option>
				<option value="TOHEDO ">TOHEDO </option>
				<option value="M/BENZ VAKA 208">M/BENZ VAKA 208</option>
				<option value="HOVER">HOVER</option>
				<option value="NISSAN COASTER">NISSAN COASTER</option>
				<option value="NISSAN COMB">NISSAN COMB</option>
				<option value="NISSAN CAPSTAR">NISSAN CAPSTAR</option>
				<option value="TOYOTA CANTER">TOYOTA CANTER</option>
				<option value="HILUX">HILUX</option>
				<option value="ISUZU CAMPOCREW">ISUZU CAMPOCREW</option>
				<option value="JAC">JAC</option>
				<option value="JAC PICK UP">JAC PICK UP</option>
				<option value="JAC BUS">JAC BUS</option>
				<option value="JAC LORRY">JAC LORRY</option>
				<option value="CANTER PICK UP">CANTER PICK UP</option>
				<option value="JAC TRUCK">JAC TRUCK</option>
				<option value="HYAUNDA">HYAUNDA</option>
				<option value="INTER TRUCK">INTER TRUCK</option>
				<option value="INFINITY G20">INFINITY G20</option>
				<option value="MAZDA 2600">MAZDA 2600</option>
				<option value="M/BENZ E420">M/BENZ E420</option>
				<option value="OPEL CORSA">OPEL CORSA</option>
				<option value="NISSAN PRAIRIE">NISSAN PRAIRIE</option>
				<option value="SEAT CAR">SEAT CAR</option>
				<option value="CHEV PRISM">CHEV PRISM</option>
				<option value="ROVER 827 S">ROVER 827 S</option>
				<option value="M/BENZ 190 V/BOOT">M/BENZ 190 V/BOOT</option>
				<option value="BMW 7304">BMW 7304</option>
				<option value="ROCK MOTORCYCLE">ROCK MOTORCYCLE</option>
				<option value="DURANGO JEEP">DURANGO JEEP</option>
				<option value="TOYOTA 4 RUNNER JEEP">TOYOTA 4 RUNNER JEEP</option>
				<option value="HYUNDAI H100">HYUNDAI H100</option>
				<option value="IVECO TIPPER">IVECO TIPPER</option>
				<option value="NISSAN 200SX">NISSAN 200SX</option>
				<option value="MASSEY FERGUSON U.K">MASSEY FERGUSON U.K</option>
				<option value="M/BENZ 300T">M/BENZ 300T</option>
				<option value="TOYOTA NISSAN">TOYOTA NISSAN</option>
				<option value="RIO">RIO</option>
				<option value="RIO SC">RIO SC</option>
				<option value="VANXHALL MIDI">VANXHALL MIDI</option>
				<option value="MERCEDES-BENZ S 550">MERCEDES-BENZ S 550</option>
				<option value="MITS CANTER">MITS CANTER</option>
				<option value="NISSAN PREMIRE">NISSAN PREMIRE</option>
				<option value="ASHOK LEYLAND 1618">ASHOK LEYLAND 1618</option>
				<option value="YOKOMATO">YOKOMATO</option>
				<option value="XIN KIA">XIN KIA</option>
				<option value="BEDFORD/TIM/LORRY">BEDFORD/TIM/LORRY</option>
				<option value="V/WAGEN AMAZON">V/WAGEN AMAZON</option>
				<option value="M/BENZ C230">M/BENZ C230</option>
				<option value="PATHFINDER">PATHFINDER</option>
				<option value="BMW 740 IL">BMW 740 IL</option>
				<option value="BMW SERIES 7">BMW SERIES 7</option>
				<option value="BMW 7 SERIES">BMW 7 SERIES</option>
				<option value="M/BENZ 1114">M/BENZ 1114</option>
				<option value="TOYOTA AVANZA">TOYOTA AVANZA</option>
				<option value="M/BENZ 1414">M/BENZ 1414</option>
				<option value="DATSUN 140J">DATSUN 140J</option>
				<option value="DAIHATSU APPLAUSE">DAIHATSU APPLAUSE</option>
				<option value="SHARPER CARAVAN">SHARPER CARAVAN</option>
				<option value="GEELY">GEELY</option>
				<option value="SUZUKI ESCUDO">SUZUKI ESCUDO</option>
				<option value="DAIMLER CHRYSLER JEEP">DAIMLER CHRYSLER JEEP</option>
				<option value="TOYOTA SERENA">TOYOTA SERENA</option>
				<option value="KIA SPORT">KIA SPORT</option>
				<option value="MIT CABSTER">MIT CABSTER</option>
				<option value="QUINGUN">QUINGUN</option>
				<option value="MITSUBISHI L200">MITSUBISHI L200</option>
				<option value="VOLKS WAGEN LT35 ">VOLKS WAGEN LT35 </option>
				<option value="NISSAN SPACE BUS">NISSAN SPACE BUS</option>
				<option value="NISSAN 200LX">NISSAN 200LX</option>
				<option value="LANTRA HYUNDAI">LANTRA HYUNDAI</option>
				<option value="VOLVO S70">VOLVO S70</option>
				<option value="V/W COMODO">V/W COMODO</option>
				<option value="NISSAN FRONTIER">NISSAN FRONTIER</option>
				<option value="V/WAGEN BORA">V/WAGEN BORA</option>
				<option value="V/WAGON">V/WAGON</option>
				<option value="NISSAN SUNNY LIFT BLACK">NISSAN SUNNY LIFT BLACK</option>
				<option value="SERENA">SERENA</option>
				<option value="HUNTER">HUNTER</option>
				<option value="HUNTER CG 125">HUNTER CG 125</option>
				<option value="FIAT IVECO">FIAT IVECO</option>
				<option value="TRANSIT BUS">TRANSIT BUS</option>
				<option value="M/BENZ E220">M/BENZ E220</option>
				<option value="CHANLIN">CHANLIN</option>
				<option value="M/BENZ 208D">M/BENZ 208D</option>
				<option value="LDV PILOT VAN">LDV PILOT VAN</option>
				<option value="PICANTO S/CAR">PICANTO S/CAR</option>
				<option value="PICANTO">PICANTO</option>
				<option value="DATSUN PANEL VANN">DATSUN PANEL VANN</option>
				<option value="DASTUN">DASTUN</option>
				<option value="LDB MINI BUS">LDB MINI BUS</option>
				<option value="ISUZU BULLION VAN">ISUZU BULLION VAN</option>
				<option value="ISUZU ASCENDER">ISUZU ASCENDER</option>
				<option value="VECTRA">VECTRA</option>
				<option value="M/BENZ 300 V/BOOTS">M/BENZ 300 V/BOOTS</option>
				<option value="CHROOKE JEEP">CHROOKE JEEP</option>
				<option value="V/W SURAN">V/W SURAN</option>
				<option value="MITSUBUSHI MIRAGE">MITSUBUSHI MIRAGE</option>
				<option value="B M W 735 SERIES">B M W 735 SERIES</option>
				<option value="NX 125 M/C">NX 125 M/C</option>
				<option value="FORD ISUZU">FORD ISUZU</option>
				<option value="APOLLO">APOLLO</option>
				<option value="HAIER THERMOCOOL">HAIER THERMOCOOL</option>
				<option value="TOYOTA COPERATION S/CAR">TOYOTA COPERATION S/CAR</option>
				<option value="VAN DAF">VAN DAF</option>
				<option value="M/BENZ JEEP">M/BENZ JEEP</option>
				<option value="BMW 5251">BMW 5251</option>
				<option value="M/BENZ 408">M/BENZ 408</option>
				<option value="VOLVO 746">VOLVO 746</option>
				<option value="LDV CONVOLT">LDV CONVOLT</option>
				<option value="B.M.W 7351">B.M.W 7351</option>
				<option value="MAZDA VAN">MAZDA VAN</option>
				<option value="DAIMLER BENZ 308">DAIMLER BENZ 308</option>
				<option value="COMBO">COMBO</option>
				<option value="IVEKO TRUCK">IVEKO TRUCK</option>
				<option value="M/BENZ 914">M/BENZ 914</option>
				<option value="IVECO TRUCK">IVECO TRUCK</option>
				<option value="MIT VALLEY BUS">MIT VALLEY BUS</option>
				<option value="MIT VALLEY">MIT VALLEY</option>
				<option value="KAMA P/UP">KAMA P/UP</option>
				<option value="KIA CAR">KIA CAR</option>
				<option value="M/BENZ 601">M/BENZ 601</option>
				<option value="ZOTYE NOMAD">ZOTYE NOMAD</option>
				<option value="SKODA OCTAVIA">SKODA OCTAVIA</option>
				<option value="TOTOTA">TOTOTA</option>
				<option value="TOYOTA PANEL VAN">TOYOTA PANEL VAN</option>
				<option value="COURIER">COURIER</option>
				<option value="DAF TIPPER LORRY">DAF TIPPER LORRY</option>
				<option value="VOLVO LORRY FI6">VOLVO LORRY FI6</option>
				<option value="M/BENZ C 180">M/BENZ C 180</option>
				<option value="M/BENZ 250">M/BENZ 250</option>
				<option value="M/BENZ  508 BUS">M/BENZ  508 BUS</option>
				<option value="NISSAN MAIMA QX">NISSAN MAIMA QX</option>
				<option value="PEUGEOT 309">PEUGEOT 309</option>
				<option value="CITY">CITY</option>
				<option value="V/W T4 TRANSPORTER BUS">V/W T4 TRANSPORTER BUS</option>
				<option value="RENAULT MEGANE">RENAULT MEGANE</option>
				<option value="NISSAN MAXIMA QX">NISSAN MAXIMA QX</option>
				<option value="CORDOBA">CORDOBA</option>
				<option value="TOYOTA COROLLA L/BACK">TOYOTA COROLLA L/BACK</option>
				<option value="MORTOR CYCLE">MORTOR CYCLE</option>
				<option value="FABIA SEDAN">FABIA SEDAN</option>
				<option value="V WAGEN AUDI">V WAGEN AUDI</option>
				<option value="M/BENZ E-CLASS">M/BENZ E-CLASS</option>
				<option value="M/BENZ 100 D BUS">M/BENZ 100 D BUS</option>
				<option value="MAZDA 2200 BUS">MAZDA 2200 BUS</option>
				<option value="TITAN AX100">TITAN AX100</option>
				<option value="RENAULT TRAFIC">RENAULT TRAFIC</option>
				<option value="LDV CONVOY">LDV CONVOY</option>
				<option value="MITSUBISHI SPACE RUNNER">MITSUBISHI SPACE RUNNER</option>
				<option value="INTER TIPPER">INTER TIPPER</option>
				<option value="M/BENZ 260E">M/BENZ 260E</option>
				<option value="M/BENZ E320">M/BENZ E320</option>
				<option value="SIENNA BUS">SIENNA BUS</option>
				<option value="GRAND CHEROKEE ">GRAND CHEROKEE </option>
				<option value="DAF TRACTOR">DAF TRACTOR</option>
				<option value="LARADO JEEP">LARADO JEEP</option>
				<option value="GOLF VOLKSWAGEN">GOLF VOLKSWAGEN</option>
				<option value="B.M.W 318">B.M.W 318</option>
				<option value="V/WAGEN P/UP">V/WAGEN P/UP</option>
				<option value="ASCONAL OPEL">ASCONAL OPEL</option>
				<option value="SUZUKI VITARA">SUZUKI VITARA</option>
				<option value="KIA SEDONA">KIA SEDONA</option>
				<option value="VOLKWAGEN BEATLE">VOLKWAGEN BEATLE</option>
				<option value="KIA SHUMA 11">KIA SHUMA 11</option>
				<option value="SPEED 11 TEC">SPEED 11 TEC</option>
				<option value="RENAULT RAPID">RENAULT RAPID</option>
				<option value="MAZDA E20 BUS">MAZDA E20 BUS</option>
				<option value="NISSAN E20 BUS">NISSAN E20 BUS</option>
				<option value="AUDI A6">AUDI A6</option>
				<option value="VOLVO 240 DL">VOLVO 240 DL</option>
				<option value="LDV 400">LDV 400</option>
				<option value="MAZDA MX-6">MAZDA MX-6</option>
				<option value="DAF LORRY">DAF LORRY</option>
				<option value="NISSAN VILLAGER">NISSAN VILLAGER</option>
				<option value="IVECO LORRY">IVECO LORRY</option>
				<option value="NISSAN SUPER">NISSAN SUPER</option>
				<option value="NISSAN STARLET">NISSAN STARLET</option>
				<option value="TIMBER LORRY">TIMBER LORRY</option>
				<option value="M/BENZ 240">M/BENZ 240</option>
				<option value="V/WAGEN VERAGON">V/WAGEN VERAGON</option>
				<option value="HYUNDAI ACCENT GLS">HYUNDAI ACCENT GLS</option>
				<option value="NISSAN SUNNY L/BACK">NISSAN SUNNY L/BACK</option>
				<option value="DAF 95 TRUCK">DAF 95 TRUCK</option>
				<option value="OKA">OKA</option>
				<option value="SINOKI SUPRA">SINOKI SUPRA</option>
				<option value="JIN BEI BUS">JIN BEI BUS</option>
				<option value="MERCEDES-BENZ 280SE">MERCEDES-BENZ 280SE</option>
				<option value="DATSUN STANZA">DATSUN STANZA</option>
				<option value="HONDA DEL SOL">HONDA DEL SOL</option>
				<option value="M/BENZ E290">M/BENZ E290</option>
				<option value="M/BENZ 1314">M/BENZ 1314</option>
				<option value="SNUBA">SNUBA</option>
				<option value="ROVER 618">ROVER 618</option>
				<option value="M /BENZ 280">M /BENZ 280</option>
				<option value="EBRO">EBRO</option>
				<option value="B.M.C.">B.M.C.</option>
				<option value="TOYOTA AVENSUS">TOYOTA AVENSUS</option>
				<option value="VOLKSWAGEN TRANSPORTER">VOLKSWAGEN TRANSPORTER</option>
				<option value="SUZUKI AH 14E">SUZUKI AH 14E</option>
				<option value="INFINITY QX56">INFINITY QX56</option>
				<option value="M/BENZ CONCORD">M/BENZ CONCORD</option>
				<option value="TOYOTA  LE">TOYOTA  LE</option>
				<option value="KIA PICK UP">KIA PICK UP</option>
				<option value="B M W530">B M W530</option>
				<option value="TOYOTA SOLARA CAMRY">TOYOTA SOLARA CAMRY</option>
				<option value="POLARSUN BUS">POLARSUN BUS</option>
				<option value="DIAHAZU  JEEP">DIAHAZU  JEEP</option>
				<option value="HYUNDAI TUCSON">HYUNDAI TUCSON</option>
				<option value="M/BENZ 300">M/BENZ 300</option>
				<option value="LEYLAND TIPPER">LEYLAND TIPPER</option>
				<option value="FORD WINDSTAR">FORD WINDSTAR</option>
				<option value="MAZDA 323 F">MAZDA 323 F</option>
				<option value="TOYOTA MINI BUS">TOYOTA MINI BUS</option>
				<option value="TIPPER TRAILER">TIPPER TRAILER</option>
				<option value="HONDA ELEMENT">HONDA ELEMENT</option>
				<option value="FORD AEROSTAR XLT">FORD AEROSTAR XLT</option>
				<option value="PE P/UP">PE P/UP</option>
				<option value="MITSUBUSHI PICK UP">MITSUBUSHI PICK UP</option>
				<option value="V/W EUROVAN">V/W EUROVAN</option>
				<option value="DATSUN C20 ">DATSUN C20 </option>
				<option value="TERANO JEEP">TERANO JEEP</option>
				<option value="TERANO ">TERANO </option>
				<option value="FORD ECONOVAN">FORD ECONOVAN</option>
				<option value="MAZDA 6">MAZDA 6</option>
				<option value="FORD FOCUS">FORD FOCUS</option>
				<option value="JETTA PASSAT">JETTA PASSAT</option>
				<option value="BAW HIACE">BAW HIACE</option>
				<option value="SUZUKI VICTARA JEEP">SUZUKI VICTARA JEEP</option>
				<option value="M BENZ TANKER">M BENZ TANKER</option>
				<option value="VOLVO TRUCK">VOLVO TRUCK</option>
				<option value="M BENZ TRACTOR">M BENZ TRACTOR</option>
				<option value="CHANA LORRY">CHANA LORRY</option>
				<option value="V/WAGEN LT 40">V/WAGEN LT 40</option>
				<option value="NISSAN SENROL">NISSAN SENROL</option>
				<option value="CHINDADI P/UP">CHINDADI P/UP</option>
				<option value="NISSAN PREVIA">NISSAN PREVIA</option>
				<option value="TOYOTA TOYOACE">TOYOTA TOYOACE</option>
				<option value="DADI P/UP">DADI P/UP</option>
				<option value="DADDY  P/UP">DADDY  P/UP</option>
				<option value="MITSUBISHI CARISMA">MITSUBISHI CARISMA</option>
				<option value="ALLOY RIM LIFAN">ALLOY RIM LIFAN</option>
				<option value="PEUGEOT 104">PEUGEOT 104</option>
				<option value="NISSAN CIVILIAN">NISSAN CIVILIAN</option>
				<option value="CERATO  1.61 S/C">CERATO  1.61 S/C</option>
				<option value="PRIZM LSI">PRIZM LSI</option>
				<option value="B M W 3 SERIES">B M W 3 SERIES</option>
				<option value="V/W TOUARAG">V/W TOUARAG</option>
				<option value="LAREDO JEEP">LAREDO JEEP</option>
				<option value="TOYOTA PREDO JEEP">TOYOTA PREDO JEEP</option>
				<option value="VANXALL ASTRAL">VANXALL ASTRAL</option>
				<option value="PICK UP">PICK UP</option>
				<option value="CHRYSLER CONCORD">CHRYSLER CONCORD</option>
				<option value="FOED IVECO">FOED IVECO</option>
				<option value="DATSUN 1500">DATSUN 1500</option>
				<option value="TATA SUMO JEEP">TATA SUMO JEEP</option>
				<option value="AUDI 200">AUDI 200</option>
				<option value="HONDA I. V   TECH">HONDA I. V   TECH</option>
				<option value="DAF 1300 P/UP">DAF 1300 P/UP</option>
				<option value="V/WAGEN 80">V/WAGEN 80</option>
				<option value="KIA OPIRUS">KIA OPIRUS</option>
				<option value="JETTE SALOON">JETTE SALOON</option>
				<option value="JETTA SALOON">JETTA SALOON</option>
				<option value="OPEL CALIBRA">OPEL CALIBRA</option>
				<option value="ISUZU P/UO">ISUZU P/UO</option>
				<option value="ISUZU P/UP">ISUZU P/UP</option>
				<option value="DATSUN CABSTAR">DATSUN CABSTAR</option>
				<option value="THOMAS FLAT FACE">THOMAS FLAT FACE</option>
				<option value="FIAT CUTROEN">FIAT CUTROEN</option>
				<option value="VOLVO S/ WAGON">VOLVO S/ WAGON</option>
				<option value="BLUE BIRD REGULAR">BLUE BIRD REGULAR</option>
				<option value="THOMAS REGULAR">THOMAS REGULAR</option>
				<option value="BOXERS BAJAJ">BOXERS BAJAJ</option>
				<option value="OGT EXPERT VAN">OGT EXPERT VAN</option>
				<option value="HONDA QUITENT">HONDA QUITENT</option>
				<option value="CERATO">CERATO</option>
				<option value="DAEWOO LUBLIN VAN">DAEWOO LUBLIN VAN</option>
				<option value="PEUGEOT 504 SR">PEUGEOT 504 SR</option>
				<option value="V/WAGEN SHAROON">V/WAGEN SHAROON</option>
				<option value="V/WAGEN LT 31">V/WAGEN LT 31</option>
				<option value="SUBARU FORESTER">SUBARU FORESTER</option>
				<option value="NISSAN FRONTER P/UP">NISSAN FRONTER P/UP</option>
				<option value="LEYLAND DAF 85">LEYLAND DAF 85</option>
				<option value="ROVER 827SI">ROVER 827SI</option>
				<option value="NISSAN GLORIA">NISSAN GLORIA</option>
				<option value="MERCEDES-BENZ 520">MERCEDES-BENZ 520</option>
				<option value="PGT EXPERS VAN">PGT EXPERS VAN</option>
				<option value="BAJAJ BM100">BAJAJ BM100</option>
				<option value="TOYOTA CAMRY LE">TOYOTA CAMRY LE</option>
				<option value="CHEVYVENTURE CHEVROLET">CHEVYVENTURE CHEVROLET</option>
				<option value="V/W PARSSENT">V/W PARSSENT</option>
				<option value="V/W PARSSENTS">V/W PARSSENTS</option>
				<option value="MATES 90">MATES 90</option>
				<option value="121">121</option>
				<option value="YINHE AX100">YINHE AX100</option>
				<option value="M/BENZ  200T">M/BENZ  200T</option>
				<option value="FEDECO BUS">FEDECO BUS</option>
				<option value="M/BENZ C320">M/BENZ C320</option>
				<option value="V/W BEETLE">V/W BEETLE</option>
				<option value="RENULT CLIO">RENULT CLIO</option>
				<option value="M/BENZ TRUCK">M/BENZ TRUCK</option>
				<option value="V/W PASSAT">V/W PASSAT</option>
				<option value="HONDA ALLA">HONDA ALLA</option>
				<option value="KOREA">KOREA</option>
				<option value="G M C SAVANA">G M C SAVANA</option>
				<option value="NISSAN CELICA">NISSAN CELICA</option>
				<option value="B M W 730">B M W 730</option>
				<option value="MAZDA B 3000 ">MAZDA B 3000 </option>
				<option value="TEC SPEED I">TEC SPEED I</option>
				<option value="HYUNDAI BUS">HYUNDAI BUS</option>
				<option value="VOLVO S60">VOLVO S60</option>
				<option value="PACKARD BUS">PACKARD BUS</option>
				<option value="NISSAN E20">NISSAN E20</option>
				<option value="TOYOTA SAFE">TOYOTA SAFE</option>
				<option value="NISSAN SANTRA">NISSAN SANTRA</option>
				<option value="RENAULT ESPACE">RENAULT ESPACE</option>
				<option value="BMW320">BMW320</option>
				<option value="BMW BUS">BMW BUS</option>
				<option value="IVECO FORD">IVECO FORD</option>
				<option value="B M W HIACE BUS">B M W HIACE BUS</option>
				<option value="M/BENZ ML320">M/BENZ ML320</option>
				<option value="LITE ACE BUS">LITE ACE BUS</option>
				<option value="HUMMER H2">HUMMER H2</option>
				<option value="TOYOTA CARINA 11 L/BACK">TOYOTA CARINA 11 L/BACK</option>
				<option value="DATSUN 160J">DATSUN 160J</option>
				<option value="MERCURY TRANSPORTER">MERCURY TRANSPORTER</option>
				<option value="FORD BUS">FORD BUS</option>
				<option value="TEC 123 M/C">TEC 123 M/C</option>
				<option value="MITSUBISHI SPACE BUS">MITSUBISHI SPACE BUS</option>
				<option value="MITSUBISHI SPACE GEAR">MITSUBISHI SPACE GEAR</option>
				<option value="BEDFORD RASCAL">BEDFORD RASCAL</option>
				<option value="TINK">TINK</option>
				<option value="CHEVROLET ASTRO BUS">CHEVROLET ASTRO BUS</option>
				<option value="MARWA M/C">MARWA M/C</option>
				<option value="SALOON WAGON">SALOON WAGON</option>
				<option value="HONDA INTERGRA">HONDA INTERGRA</option>
				<option value="M/BENZ 200 TE">M/BENZ 200 TE</option>
				<option value="M/BENZ 200 V.BOOT">M/BENZ 200 V.BOOT</option>
				<option value="HONDA CR-V">HONDA CR-V</option>
				<option value="HAICE JUMBER BUS">HAICE JUMBER BUS</option>
				<option value="TOYOTA CARMRY">TOYOTA CARMRY</option>
				<option value="M/BENZ C200">M/BENZ C200</option>
				<option value="PLYMOUNT">PLYMOUNT</option>
				<option value="DODGE GRAND">DODGE GRAND</option>
				<option value="LICON ALOY">LICON ALOY</option>
				<option value="HOUSTON TRUCK">HOUSTON TRUCK</option>
				<option value="HOLSTENE">HOLSTENE</option>
				<option value="KIA CAPITAL">KIA CAPITAL</option>
				<option value="KIA LORRY K2700SC">KIA LORRY K2700SC</option>
				<option value="MERCEDES-BENZ ML500">MERCEDES-BENZ ML500</option>
				<option value="MAGRUS">MAGRUS</option>
				<option value="OCTONIA">OCTONIA</option>
				<option value="INFINITY JEEP">INFINITY JEEP</option>
				<option value="TACOMA">TACOMA</option>
				<option value="TOYOTA MICRA">TOYOTA MICRA</option>
				<option value="NIVA 1600">NIVA 1600</option>
				<option value="B M W 525I">B M W 525I</option>
				<option value="STEYR TRUCK">STEYR TRUCK</option>
				<option value="FORD FIESTA">FORD FIESTA</option>
				<option value="IVECO SEDDON ATKINSON TANKER">IVECO SEDDON ATKINSON TANKER</option>
				<option value="CHEVROLET CAVALIER">CHEVROLET CAVALIER</option>
				<option value="MERCEDES-BENZ 310">MERCEDES-BENZ 310</option>
				<option value="GOLDEN">GOLDEN</option>
				<option value="MAZDA B2200">MAZDA B2200</option>
				<option value="HOVAN BUS">HOVAN BUS</option>
				<option value="FORD AEROSTAR BUS">FORD AEROSTAR BUS</option>
				<option value="VOLKSWAGEN SCHIROCO">VOLKSWAGEN SCHIROCO</option>
				<option value="STYRE">STYRE</option>
				<option value="HYUNDAI EXCEL">HYUNDAI EXCEL</option>
				<option value="FORD MUSTANG">FORD MUSTANG</option>
				<option value="TEE CYCLE">TEE CYCLE</option>
				<option value="AUSTIN TIPPER">AUSTIN TIPPER</option>
				<option value="BMW 328">BMW 328</option>
				<option value="MACK CH612">MACK CH612</option>
				<option value="B M W 528">B M W 528</option>
				<option value="FIAT PUNTO">FIAT PUNTO</option>
				<option value="GOLF 11">GOLF 11</option>
				<option value="MAZDA CABIN P/UP">MAZDA CABIN P/UP</option>
				<option value="MAZDA CABIN">MAZDA CABIN</option>
				<option value="MERCEDES TRUCK">MERCEDES TRUCK</option>
				<option value="SIMBA KARY-GO">SIMBA KARY-GO</option>
				<option value="G M C VAN">G M C VAN</option>
				<option value="SIMBA TRICYCLE">SIMBA TRICYCLE</option>
				<option value="BC125-7">BC125-7</option>
				<option value="BASCO">BASCO</option>
				<option value="DAF 1700">DAF 1700</option>
				<option value="DAF 1700 TRUCK">DAF 1700 TRUCK</option>
				<option value="DEER 4X2 SINGLE CABIN P/UP">DEER 4X2 SINGLE CABIN P/UP</option>
				<option value="MITS P/UP">MITS P/UP</option>
				<option value="VOLVO V40">VOLVO V40</option>
				<option value="CHEVY P UP">CHEVY P UP</option>
				<option value="M/BENZ V-BOOT">M/BENZ V-BOOT</option>
				<option value="TOYOTA LIYEACE">TOYOTA LIYEACE</option>
				<option value="FORD COUGAR">FORD COUGAR</option>
				<option value="MERCEDE 1017 TRUCK">MERCEDE 1017 TRUCK</option>
				<option value="MERCEDES 1017 TUCK">MERCEDES 1017 TUCK</option>
				<option value="TOYOTA HYLANDER">TOYOTA HYLANDER</option>
				<option value="BOXER BM100">BOXER BM100</option>
				<option value="M/BENZ 809">M/BENZ 809</option>
				<option value="TATA P/UP">TATA P/UP</option>
				<option value="JINSSUN">JINSSUN</option>
				<option value="KINGCHENG">KINGCHENG</option>
				<option value="PRIZM GEO">PRIZM GEO</option>
				<option value="ISUZU JEEP">ISUZU JEEP</option>
				<option value="DOUBLE CABIN">DOUBLE CABIN</option>
				<option value="DATSUN 180B S/W">DATSUN 180B S/W</option>
				<option value="NISSAN DIESEL">NISSAN DIESEL</option>
				<option value="MAZDA XEDOS-6">MAZDA XEDOS-6</option>
				<option value="OPEL FROTERA">OPEL FROTERA</option>
				<option value="CARTER CY 90">CARTER CY 90</option>
				<option value="PRADO JEEP">PRADO JEEP</option>
				<option value="SIGMA">SIGMA</option>
				<option value="NISSAN MAXIINIA">NISSAN MAXIINIA</option>
				<option value="NISSAN MAXINIA">NISSAN MAXINIA</option>
				<option value="BEDFORD TIPPER">BEDFORD TIPPER</option>
				<option value="MARCHETTI TERRIN">MARCHETTI TERRIN</option>
				<option value="LIBERTY">LIBERTY</option>
				<option value="NISSAN TRADE">NISSAN TRADE</option>
				<option value="LOWBED">LOWBED</option>
				<option value="INFINITY CAR">INFINITY CAR</option>
				<option value="COROLLA">COROLLA</option>
				<option value="ZHONEGYU">ZHONEGYU</option>
				<option value="FORD SILHOUTTE ">FORD SILHOUTTE </option>
				<option value="TUYOTA">TUYOTA</option>
				<option value="M/BENZ MI 350/R">M/BENZ MI 350/R</option>
				<option value="DAKOTA DODGE">DAKOTA DODGE</option>
				<option value="M/BENZ 208 BUS">M/BENZ 208 BUS</option>
				<option value="BOXER B M">BOXER B M</option>
				<option value="SUZI MIDI">SUZI MIDI</option>
				<option value="ROVEER 75">ROVEER 75</option>
				<option value="MIT ECLIPSE">MIT ECLIPSE</option>
				<option value="TOYOTA CABSTER">TOYOTA CABSTER</option>
				<option value="CHEROOKE ">CHEROOKE </option>
				<option value="VAUXHALL ">VAUXHALL </option>
				<option value="NISSAN TEANA">NISSAN TEANA</option>
				<option value="MALIBU CHEVROLET">MALIBU CHEVROLET</option>
				<option value="AUDI Q7">AUDI Q7</option>
				<option value="FOED CLUB">FOED CLUB</option>
				<option value="FORD CLUBWAGEN">FORD CLUBWAGEN</option>
				<option value="TOYOTA SOLARA">TOYOTA SOLARA</option>
				<option value="LIBERTY SPORT JEEP">LIBERTY SPORT JEEP</option>
				<option value="MIT SPACE BUS">MIT SPACE BUS</option>
				<option value="MITSUBISHI BUS">MITSUBISHI BUS</option>
				<option value="FORD PROBE">FORD PROBE</option>
				<option value="TOYOTA T100">TOYOTA T100</option>
				<option value="TOYOTA T100 P/UP">TOYOTA T100 P/UP</option>
				<option value="M/BENZE ML430">M/BENZE ML430</option>
				<option value="M/BENZE ML 430">M/BENZE ML 430</option>
				<option value="M/B ML 430">M/B ML 430</option>
				<option value="M/B">M/B</option>
				<option value="M/BENZ V BOOT">M/BENZ V BOOT</option>
				<option value="LEXUS LX 400">LEXUS LX 400</option>
				<option value="NISSAN CABIN ">NISSAN CABIN </option>
				<option value="INDIGO GLX">INDIGO GLX</option>
				<option value="MIT L200 PICK UP">MIT L200 PICK UP</option>
				<option value="SAMYANG">SAMYANG</option>
				<option value="SCODA OCTAVIA">SCODA OCTAVIA</option>
				<option value="SEPHIRE S/C">SEPHIRE S/C</option>
				<option value="RENAULT BUS">RENAULT BUS</option>
				<option value="ZONG CHING">ZONG CHING</option>
				<option value="WANHU KARY GO">WANHU KARY GO</option>
				<option value="DUCAR 110-2">DUCAR 110-2</option>
				<option value="V/WAGEN AUDI">V/WAGEN AUDI</option>
				<option value="TELECOLINE">TELECOLINE</option>
				<option value="AERONAUTIC HAICE BUS">AERONAUTIC HAICE BUS</option>
				<option value="MARCU VILL">MARCU VILL</option>
				<option value="NX 125 ">NX 125 </option>
				<option value="SEAT TOLEDO">SEAT TOLEDO</option>
				<option value="HONDA SUPER">HONDA SUPER</option>
				<option value="B M W JEEP">B M W JEEP</option>
				<option value="DAF 1100">DAF 1100</option>
				<option value="V/WAGEN TRANSPORTER">V/WAGEN TRANSPORTER</option>
				<option value="KARIGO TRICYCLE">KARIGO TRICYCLE</option>
				<option value="MAN DIESEL TIPPER">MAN DIESEL TIPPER</option>
				<option value="MAC CHUKS">MAC CHUKS</option>
				<option value="MI 350 JEEP">MI 350 JEEP</option>
				<option value="DUKAR 3WHEELERS">DUKAR 3WHEELERS</option>
				<option value="DUKAR 3 WHEELER">DUKAR 3 WHEELER</option>
				<option value="DODGE NEON">DODGE NEON</option>
				<option value="MERCEDES-BENZ 230T">MERCEDES-BENZ 230T</option>
				<option value="DASHATSU APPLAUSE">DASHATSU APPLAUSE</option>
				<option value="DODGE DURANGO">DODGE DURANGO</option>
				<option value="OPEL KADET  S/W">OPEL KADET  S/W</option>
				<option value="TOYOTA ARISTO">TOYOTA ARISTO</option>
				<option value="ROVER 216 GST">ROVER 216 GST</option>
				<option value="TOYOTA CARINA II">TOYOTA CARINA II</option>
				<option value="SSANG YOUNG REXTON">SSANG YOUNG REXTON</option>
				<option value="M/BENZ G500">M/BENZ G500</option>
				<option value="HYUNDAI PICK UP">HYUNDAI PICK UP</option>
				<option value="V/WAGEN TOUAREG JEEP">V/WAGEN TOUAREG JEEP</option>
				<option value="BOXER">BOXER</option>
				<option value="QINOI">QINOI</option>
				<option value="VOLVO V70XCS/WAGON">VOLVO V70XCS/WAGON</option>
				<option value="BRILLIANCE SPLENDOR">BRILLIANCE SPLENDOR</option>
				<option value="NISSAN TILDA">NISSAN TILDA</option>
				<option value="M/BENZ VITO">M/BENZ VITO</option>
				<option value="LEYLAND SCRAB LORRY">LEYLAND SCRAB LORRY</option>
				<option value="DATSUN BUS">DATSUN BUS</option>
				<option value="LAND ROVER FREELANDER">LAND ROVER FREELANDER</option>
				<option value="QINGQI INNOSON">QINGQI INNOSON</option>
				<option value="HYUNDAI SANTAMO">HYUNDAI SANTAMO</option>
				<option value="CRUISER CARGO ">CRUISER CARGO </option>
				<option value="M/BENZ ML 430">M/BENZ ML 430</option>
				<option value="CY 90 SPOKE">CY 90 SPOKE</option>
				<option value="GK 125">GK 125</option>
				<option value="SUZUKI GRAND VITARA">SUZUKI GRAND VITARA</option>
				<option value="ISUZU BEDFORD BUS">ISUZU BEDFORD BUS</option>
				<option value="V/WAGEN L 48">V/WAGEN L 48</option>
				<option value="V/WAGEN LT 28 P/UP">V/WAGEN LT 28 P/UP</option>
				<option value="RANGE ROVER VOGUE">RANGE ROVER VOGUE</option>
				<option value="M/BENZ TANKER TRUCK">M/BENZ TANKER TRUCK</option>
				<option value="CHEVROLET OPTRA 5">CHEVROLET OPTRA 5</option>
				<option value="IVECO EUROSTAR TRACTOR HEAD">IVECO EUROSTAR TRACTOR HEAD</option>
				<option value="M/BENZ VAN">M/BENZ VAN</option>
				<option value="HONDA ODYSSEY SPACE BUS">HONDA ODYSSEY SPACE BUS</option>
				<option value="OPEL CORSA 10">OPEL CORSA 10</option>
				<option value="STEYER">STEYER</option>
				<option value="PRIZM S/CAR">PRIZM S/CAR</option>
				<option value="TOYOTA MATRIX">TOYOTA MATRIX</option>
				<option value="V/WAGEN MINITRUCK">V/WAGEN MINITRUCK</option>
				<option value="TOYOTA LEXUS LS 470">TOYOTA LEXUS LS 470</option>
				<option value="MAZDA XEDO 36">MAZDA XEDO 36</option>
				<option value="V/WAGEN LT 45">V/WAGEN LT 45</option>
				<option value="FORD F150 JEEP">FORD F150 JEEP</option>
				<option value="M/BENZ S/WAGON">M/BENZ S/WAGON</option>
				<option value="MIT PAJERO">MIT PAJERO</option>
				<option value="DODGE GRAND CARAVAN">DODGE GRAND CARAVAN</option>
				<option value="TOYOTA SEQUOIA">TOYOTA SEQUOIA</option>
				<option value="GO WELL M/C">GO WELL M/C</option>
				<option value="FORD GALAXY">FORD GALAXY</option>
				<option value="FANAGON VOLK">FANAGON VOLK</option>
				<option value="SUBARU PROTON">SUBARU PROTON</option>
				<option value="FORD P/UP">FORD P/UP</option>
				<option value="RENAULT LAGUNA LIFT BACK">RENAULT LAGUNA LIFT BACK</option>
				<option value="M/BENZ R350">M/BENZ R350</option>
				<option value="ATUL 3WHEELER">ATUL 3WHEELER</option>
				<option value="HYUNDA">HYUNDA</option>
				<option value="CIELO DAEWOO">CIELO DAEWOO</option>
				<option value="SEDDON ATKINSON">SEDDON ATKINSON</option>
				<option value="MERCURY COMM VAN">MERCURY COMM VAN</option>
				<option value="LICON NAVIGATOR JEEP">LICON NAVIGATOR JEEP</option>
				<option value="LINCON NAVIGATOR JEEP">LINCON NAVIGATOR JEEP</option>
				<option value="B. M. W  316 S/CAR">B. M. W  316 S/CAR</option>
				<option value="B MW 316">B MW 316</option>
				<option value="VOLVO 200">VOLVO 200</option>
				<option value="NISSAN SANZA">NISSAN SANZA</option>
				<option value="VOLVO BOX">VOLVO BOX</option>
				<option value="DAF XF 430">DAF XF 430</option>
				<option value="MAGRUIS DEUTZ">MAGRUIS DEUTZ</option>
				<option value="LANCIA KAPPA">LANCIA KAPPA</option>
				<option value="FORD ECONOMOVAN BUS">FORD ECONOMOVAN BUS</option>
				<option value="V/W GOLF">V/W GOLF</option>
				<option value="WINDSTAR FORD">WINDSTAR FORD</option>
				<option value="TEC SPEED ">TEC SPEED </option>
				<option value="MAN TRUCK TIPPER">MAN TRUCK TIPPER</option>
				<option value="KYMCO MC">KYMCO MC</option>
				<option value="PREVIA">PREVIA</option>
				<option value="FORD AEROSTAR S/BUS">FORD AEROSTAR S/BUS</option>
				<option value="VOLVO 580">VOLVO 580</option>
				<option value="TOYOTA LIMITED JEEP">TOYOTA LIMITED JEEP</option>
				<option value="CHRYSLER NEON">CHRYSLER NEON</option>
				<option value="OPEL SERATO">OPEL SERATO</option>
				<option value="MORRIS TIMBER ">MORRIS TIMBER </option>
				<option value="OPEL VAVXHEULT">OPEL VAVXHEULT</option>
				<option value="OPEL VANXHEULT">OPEL VANXHEULT</option>
				<option value="TOYOTA DYNA 200 PICK UP">TOYOTA DYNA 200 PICK UP</option>
				<option value="SAVANA BUS">SAVANA BUS</option>
				<option value="TRACTOR">TRACTOR</option>
				<option value="ACURA TI 3.2">ACURA TI 3.2</option>
				<option value="SUZUKI SIDE KICK">SUZUKI SIDE KICK</option>
				<option value="MAZDA 322">MAZDA 322</option>
				<option value="SINO">SINO</option>
				<option value="LEXUS RX 330">LEXUS RX 330</option>
				<option value="FORD ECONOLINE">FORD ECONOLINE</option>
				<option value="MAZDA HILUX">MAZDA HILUX</option>
				<option value="INFINITY Q45">INFINITY Q45</option>
				<option value="LIFTAN ">LIFTAN </option>
				<option value="LIFTAN MOTORCYCLE">LIFTAN MOTORCYCLE</option>
				<option value="STYER TIPPER">STYER TIPPER</option>
				<option value="PEUGEOT P/UP">PEUGEOT P/UP</option>
				<option value="FORD ESCORT WAGON">FORD ESCORT WAGON</option>
				<option value="ARMADA JEEP">ARMADA JEEP</option>
				<option value="TOYOTA DYNA P/UP">TOYOTA DYNA P/UP</option>
				<option value="NISSAN CARAVAN BUS">NISSAN CARAVAN BUS</option>
				<option value="LANDWIND">LANDWIND</option>
				<option value="CHANGHE">CHANGHE</option>
				<option value="ROEWE">ROEWE</option>
				<option value="HONGQI">HONGQI</option>
				<option value="ZOTYE">ZOTYE</option>
				<option value="GREEN FIELD MOTOR">GREEN FIELD MOTOR</option>
				<option value="GUIZHOU / YUNQUE">GUIZHOU / YUNQUE</option>
				<option value="SOUEAST MOTORS&nbsp;/&nbsp;DONGNAN">SOUEAST MOTORS&nbsp;/&nbsp;DONGNAN</option>
				<option value="HWANGHAI">HWANGHAI</option>
				<option value="ZXAUTO">ZXAUTO</option>
				<option value="CHERY">CHERY</option>
				<option value="QOROS">QOROS</option>
				<option value="FUQI">FUQI</option>
				<option value="GREAT WALL">GREAT WALL</option>
				<option value="HAIMA">HAIMA</option>
				<option value="NANJING SOYAT">NANJING SOYAT</option>
				<option value="CHANG'AN">CHANG'AN</option>
				<option value="ZHONGYU">ZHONGYU</option>
				<option value="GAIG">GAIG</option>
				<option value="JMC">JMC</option>
				<option value="BAIC">BAIC</option>
				<option value="DONGFENG">DONGFENG</option>
				<option value="BYD">BYD</option>
				<option value="BAOLONG">BAOLONG</option>
				<option value="SAIC MOTOR">SAIC MOTOR</option>
				<option value="KING LONG">KING LONG</option>
				<option value="YUTONG">YUTONG</option>
				<option value="TIANMA">TIANMA</option>
				<option value="HAFEI">HAFEI</option>
				<option value="GONOW">GONOW</option>
				<option value="EVERUS">EVERUS</option>
				<option value="YOUNGMAN">YOUNGMAN</option>
				<option value="FORTA">FORTA</option>
				<option value="POLARSUN AUTOMOBILE">POLARSUN AUTOMOBILE</option>
				<option value="CHANA">CHANA</option>
				<option value="BRILLIANCE">BRILLIANCE</option>
				<option value="SICHUAN TENGZHONG">SICHUAN TENGZHONG</option>
				<option value="FUXING">FUXING</option>
				<option value="DADI">DADI</option>
				<option value="BAW">BAW</option>
				<option value="HUALI">HUALI</option>
				<option value="FAW">FAW</option>
				<option value="TONGTIAN">TONGTIAN</option>
				<option value="SHAANXI">SHAANXI</option>
				<option value="SHUANGHUAN">SHUANGHUAN</option>
				<option value="HUAYANG">HUAYANG</option>
				<option value="JONWAY">JONWAY</option>
				<option value="SMA">SMA</option>
				<option value="FUKANG">FUKANG</option>
				<option value="NAC">NAC</option>
				<option value="GAC">GAC</option>
				<option value="HAWTAI (HUATAI)">HAWTAI (HUATAI)</option>
                  </select>
                </div>			
		 </div>
		<div class="col-md-6">
		        <div class="input-group mb-3">
  <select class="form-control select2" required name="regtype"  style="width: 100%;" required name="parent_cat" id="parent_cat">
   <option disabled="disabled" selected="selected" value=''>Registration Type</option>
        <?php while($row = mysqli_fetch_array($query_parent)): ?>
        <option value="<?php echo $row['idRegType']; ?>"><?php echo $row['RegType']; ?></option>
        <?php endwhile; ?>
    </select>	
                </div>			
        </div>		
	  </div>
	<div class="row">
	    <div class="col-md-6">
		        		        <div class="input-group mb-3">
<select class="form-control select2" style="width: 100%;"  required name="vehicletype"  id="asdf_cat"></select>
                </div>		
		 </div>
		<div class="col-md-6">
		        <div class="input-group mb-3">
<select class="form-control select2" style="width: 100%;"  required name="amount_to_pay" id="sub_cat" required></select>	
                </div>			
        </div>		
	  </div>
 	<div class="row">
	    <div class="col-md-6">
        <div class="input-group mb-3">
          <input type="text" class="form-control" required name="fullname" placeholder="Full Name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>	
		 </div>
		 	    <div class="col-md-6">

        <div class="input-group mb-3">
				  <select class="form-control select2" required name="gender" style="width: 100%;">
                    <option value="" selected="selected"> Select Gender </option>
                    <option>Male</option>
                    <option>Female</option>
                  </select>
                </div>
	  </div>				
	  </div>
 	  <div class="row">
	    <div class="col-md-6">
        <div class="input-group mb-3">
          <input type="text" class="form-control" required name="phoneno" placeholder="Phone No">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-phone"></span>
            </div>
          </div>
        </div>	
        <div class="input-group mb-3">
          <input type="text" class="form-control" required name="homeaddr" placeholder="Home Address">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-square"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" required name="password"  placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>			
		</div>
		
		<div class="col-md-6">
        <div class="input-group mb-3">
          <input type="email" class="form-control" required name="email"  placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
				  <select class="form-control select2" required name="hometwon"  style="width: 100%;">
                    <option value="" selected="selected"> Select Home Town </option>
                    <option>Anka</option>
                    <option>Bakure</option>
                    <option>Bukkuyum</option>
					<option>Bungudo</option>
                    <option>Gumi</option>
                    <option>Gusau</option>
					<option>Isa</option>
                    <option>Kaura-Namoda</option>
                    <option>Kiyawa</option>
					 <option>Maradun</option>
                    <option>Marau</option>
                    <option>Shinkafa</option>
					 <option>Talata-Mafara</option>
                    <option>Tsafe</option>
                    <option>Zurmi</option>
                  </select>
                </div>	
	        <div class="input-group mb-3">
          <input type="password" class="form-control" required name="cpassword" placeholder="Retype password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>			
        </div>			
	  </div>
	  </div>


	


        </div>


        <div class="row">
          <div class="col-8">
      <a href="index.php?user=logout" class="text-center">I already have an account</a>
		  
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" name="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>


    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->